'use client'
import { useState } from 'react'
import { EmptyState, KpiCard, KpiRow, PageHeader } from '@plataforma/ui-bridge'
import { appPath } from '@/lib/base-path'
type Config={campaign_id:string;campaign:string;p0_threshold:number;p1_threshold:number;p2_threshold:number;lambda_freshness:number;source_weights:Record<string,number>}
const sources=['instagram_comment','instagram_follower','instagram_dm','threads','reddit','email','whatsapp']
export function ConfigsClient({config}:{config:Config}){
 const[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[impact,setImpact]=useState<{total:number;priority_changes:number}|null>(null)
 if(!config)return <main className="page"><PageHeader title="Configurações" subtitle="Scoring e prioridade por campanha"/><EmptyState message="Selecione uma campanha com configuração de scoring."/></main>
 async function submit(formElement:HTMLFormElement,preview:boolean){setBusy(preview?'preview':'save');setMessage('');const form=new FormData(formElement);const payload={campaignId:config.campaign_id,weights:Object.fromEntries(sources.map(source=>[source,Number(form.get(source)??1)])),thresholds:{p0:Number(form.get('p0')),p1:Number(form.get('p1')),p2:Number(form.get('p2'))},preview};try{const response=await fetch(appPath('/api/admin/configs'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json() as {impact?:{total:number;priority_changes:number};error?:string};if(!response.ok)throw new Error(body.error??'Não foi possível aplicar');if(preview&&body.impact){setImpact(body.impact);setMessage('Prévia calculada com os scores reais da campanha.')}else setMessage('Configuração salva e auditada.')}catch(error){setMessage(error instanceof Error?error.message:'Erro inesperado')}finally{setBusy('')}}
 return <main className="page"><PageHeader title="Configurações" subtitle={`Scoring e prioridade · ${config.campaign}`}/><KpiRow><KpiCard label="Limite P0" value={config.p0_threshold}/><KpiCard label="Limite P1" value={config.p1_threshold}/><KpiCard label="Limite P2" value={config.p2_threshold}/><KpiCard label="Decaimento" value={config.lambda_freshness}/></KpiRow><form className="config-form" onSubmit={event=>{event.preventDefault();void submit(event.currentTarget,false)}}><section className="card"><h2>Faixas de prioridade</h2><p>Os limites precisam permanecer em ordem decrescente.</p><div className="threshold-grid"><label>P0<input name="p0" type="number" min="0" max="100" defaultValue={config.p0_threshold}/></label><label>P1<input name="p1" type="number" min="0" max="100" defaultValue={config.p1_threshold}/></label><label>P2<input name="p2" type="number" min="0" max="100" defaultValue={config.p2_threshold}/></label></div></section><section className="card"><h2>Peso por origem</h2><div className="weight-grid">{sources.map(source=><label key={source}>{source.replace(/_/g,' ')}<input name={source} type="number" min="0" max="10" step="0.1" defaultValue={config.source_weights?.[source]??1}/></label>)}</div></section>{impact&&<section className="card impact-preview"><h2>Impacto da prévia</h2><strong>{impact.priority_changes} de {impact.total}</strong><p>leads mudariam de prioridade com os novos limites. Os pesos serão aplicados no próximo recálculo do worker.</p></section>}<div className="action-row"><button type="button" disabled={Boolean(busy)} onClick={event=>event.currentTarget.form&&void submit(event.currentTarget.form,true)}>{busy==='preview'?'Calculando…':'Calcular prévia'}</button><button disabled={Boolean(busy)}>{busy==='save'?'Salvando…':'Salvar configuração'}</button></div><p role="status">{message}</p></form></main>
}
