import { createDatabase } from '@plataforma/db'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireRole } from '@/lib/permissions'
const CreateSchema=z.object({campaignId:z.string().uuid(),username:z.string().trim().regex(/^@?[A-Za-z0-9._]{1,30}$/),weight:z.number().min(0).max(5).default(1),notes:z.string().max(1000).optional()})
const UpdateSchema=z.object({campaignId:z.string().uuid(),competitorId:z.string().uuid(),status:z.enum(['active','paused','archived']).optional(),weight:z.number().min(0).max(5).optional()})
export async function GET(){await requireRole('viewer');const{pool}=createDatabase(process.env.DATABASE_URL!);try{return NextResponse.json({items:(await pool.query(`SELECT c.*,cc.campaign_id,cc.weight,cc.status AS campaign_status FROM competitors c JOIN campaign_competitors cc ON cc.competitor_id=c.id ORDER BY c.username`)).rows})}finally{}}
export async function POST(request:Request){const user=await requireRole('operator');const parsed=CreateSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'invalid_body',issues:parsed.error.flatten()},{status:400});const{campaignId,username,weight,notes}=parsed.data;const{pool}=createDatabase(process.env.DATABASE_URL!);const client=await pool.connect();try{await client.query('BEGIN');const competitor=await client.query(`INSERT INTO competitors(username,added_by_user_id,notes)VALUES($1,$2,$3) ON CONFLICT(username)DO UPDATE SET notes=COALESCE(EXCLUDED.notes,competitors.notes) RETURNING id`,[username.replace(/^@/,''),user.email,notes]);await client.query(`INSERT INTO campaign_competitors(campaign_id,competitor_id,added_by_user_id,weight)VALUES($1,$2,$3,$4) ON CONFLICT(campaign_id,competitor_id)DO UPDATE SET status='active',weight=EXCLUDED.weight`,[campaignId,competitor.rows[0].id,user.email,weight]);await client.query(`INSERT INTO audit_log(actor_id,action,target,after)VALUES($1,'competitor.add',$2,$3)`,[user.email,competitor.rows[0].id,{campaignId,username,weight}]);await client.query('COMMIT');return NextResponse.json({id:competitor.rows[0].id},{status:201})}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
export async function PATCH(request:Request){const user=await requireRole('operator');const parsed=UpdateSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'invalid_body',issues:parsed.error.flatten()},{status:400});const b=parsed.data;const{pool}=createDatabase(process.env.DATABASE_URL!);try{const before=await pool.query('SELECT * FROM campaign_competitors WHERE campaign_id=$1 AND competitor_id=$2',[b.campaignId,b.competitorId]);if(!before.rowCount)return NextResponse.json({error:'not_found'},{status:404});const result=await pool.query(`UPDATE campaign_competitors SET status=COALESCE($3,status),weight=COALESCE($4,weight) WHERE campaign_id=$1 AND competitor_id=$2 RETURNING *`,[b.campaignId,b.competitorId,b.status??null,b.weight??null]);await pool.query(`UPDATE competitors SET status=COALESCE($2,status) WHERE id=$1`,[b.competitorId,b.status??null]);await pool.query(`INSERT INTO audit_log(actor_id,action,target,before,after)VALUES($1,'competitor.update',$2,$3,$4)`,[user.email,b.competitorId,before.rows[0],result.rows[0]]);return NextResponse.json({item:result.rows[0]})}finally{}}
