import type { TextProvider } from '@/lib/ai/providers/types'
import { compareContent } from './similarity'
import { evaluateQuality } from './quality'
import { selectEditorialTemplate } from './template-selector'
import { buildCopyPrompt, splitCopyUnits, toContentFormat } from './copy-contracts'

export interface EditorialContext { thesis: { id: string; title: string; coreStatement: string; forbiddenWords?: string[] | null; tone?: string | null }; planItem: { format: string; hookStrategy?: string | null; cta?: string | null; visualDirection?: string | null }; argument?: { content: string } | null; knowledge?: Array<{ content: string }> }
export function buildContext(context: EditorialContext) { return context }
export function generateBrief(context: EditorialContext) { return { format: context.planItem.format, coreArgument: context.argument?.content ?? context.thesis.coreStatement, hook: context.planItem.hookStrategy ?? `Uma perspectiva prática sobre ${context.thesis.title}`, cta: context.planItem.cta, visualDirection: context.planItem.visualDirection ?? 'Design limpo, hierarquia forte e contraste de marca.', supportingPoints: context.knowledge?.slice(0, 3).map((item) => item.content) ?? [] } }
export async function generateCopy(brief: ReturnType<typeof generateBrief>, context: EditorialContext, provider?: TextProvider) { const format = toContentFormat(brief.format); const prompt = buildCopyPrompt({ format, thesis: context.thesis.coreStatement, argument: brief.coreArgument, hook: brief.hook, tone: context.thesis.tone, supportingPoints: brief.supportingPoints, cta: brief.cta }); const generated = provider?.isConfigured() ? (await provider.generate({ prompt, maxTokens: 1200, temperature: .6 })).text : `${brief.hook}\n\n${brief.coreArgument}\n\n${brief.supportingPoints.join('\n')}\n\n${brief.cta ?? ''}`; const copyData = format === 'carousel' ? { headline: brief.hook, slides: splitCopyUnits(generated, '[[CARD]]'), cta: brief.cta } : format === 'story' ? { frames: splitCopyUnits(generated, '[[FRAME]]'), cta: brief.cta } : { headline: brief.hook, body: generated, cta: brief.cta }; return { text: generated, copyData, approvalRequired: true as const } }
export function validateBrief(brief: ReturnType<typeof generateBrief>) { return { valid: Boolean(brief.coreArgument && brief.hook), errors: [] as string[] } }
export function reviewCopy(copy: { text: string }, brief: ReturnType<typeof generateBrief>, context: EditorialContext, similarity = 0) { return evaluateQuality({ text: copy.text, coreStatement: context.thesis.coreStatement, forbiddenWords: context.thesis.forbiddenWords ?? [], cta: brief.cta, format: brief.format, similarity, hook: brief.hook }) }
export function calculateSimilarity(copy: { text: string }, recent: Array<{ text: string }>) { return recent.map((item) => compareContent({ text: copy.text }, item)).sort((a, b) => b.semantic - a.semantic)[0] }
export function selectTemplate(copy: { text: string }, context: EditorialContext, recentTemplateIds: string[] = []) { return selectEditorialTemplate({ format: context.planItem.format, text: copy.text, recentTemplateIds }) }
export function rewriteIfNeeded(copy: { text: string }, score: { overall: number }, reason?: string) { return score.overall >= .65 ? { ...copy, needsRevision: false as const } : { ...copy, needsRevision: true as const, revisionReason: reason ?? 'Revise a clareza e torne a mensagem mais específica.' } }
