'use client'
import { useEffect, useRef, useState } from 'react'
import { EmptyState, PageHeader, StatusBadge } from '@plataforma/ui-bridge'
import { appPath } from '@/lib/base-path'
export default function CreativeBridge(){
 const[payload,setPayload]=useState<Record<string,unknown>|null>(null),[status,setStatus]=useState('Carregando oportunidade…'),editor=useRef<Window|null>(null)
 useEffect(()=>{const opportunity=new URLSearchParams(location.search).get('opportunity');if(opportunity)fetch(appPath(`/api/content-opportunities/${opportunity}/creative`)).then(async response=>{const body=await response.json() as {payload?:Record<string,unknown>;error?:string};if(!response.ok||!body.payload)throw new Error(body.error??'Oportunidade indisponível');setPayload(body.payload);setStatus('Criativo preparado para o editor')}).catch(error=>setStatus(error instanceof Error?error.message:'Erro ao carregar'));window.opener?.postMessage({type:'creative-bridge-ready'},location.origin)},[])
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin!==location.origin)return;if(event.data?.type==='content-opportunity'&&event.data.payload&&typeof event.data.payload==='object'){setPayload(event.data.payload as Record<string,unknown>);setStatus('Criativo preparado para o editor')}if(event.data?.type==='design-system-ready'&&payload){(event.source as Window|null)?.postMessage({type:'editor-prefill',payload},{targetOrigin:location.origin});setStatus('Conteúdo entregue ao editor')}if(event.data?.type==='editor-prefill-received')setStatus('Editor carregou o conteúdo')};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[payload])
 function openEditor(){if(!payload)return;editor.current=window.open('/design-system','design-system');setStatus(editor.current?'Abrindo editor…':'O navegador bloqueou a nova janela. Libere pop-ups e tente novamente.')}
 return <main className="page"><PageHeader title="Ponte criativa" subtitle="Transferência segura da oportunidade para o editor visual"/><section className="card creative-preview"><StatusBadge status={status}/>{payload?<><p className="eyebrow">{String(payload.eyebrow??'Oportunidade')}</p><h2>{String(payload.title??'Sem título')}</h2><p>{String(payload.body??'Sem texto principal')}</p><details><summary>Legenda e evidências</summary><p>{String(payload.caption??'Nenhuma evidência')}</p></details><button onClick={openEditor}>Abrir no editor visual</button></>:<EmptyState message={status}/>}</section></main>
}
