import { createDatabase } from '@plataforma/db'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireRole } from '@/lib/permissions'

const TriggerSchema=z.object({id:z.string().uuid().optional(),name:z.string().min(2).max(120),matchExpr:z.string().min(1).max(1000),severity:z.enum(['info','warn','error','critical']),channels:z.array(z.string().min(1)).default([]),throttleSeconds:z.number().int().min(0).max(604800).default(300),active:z.boolean().default(true)})
export async function GET(){await requireRole('viewer');const{pool}=createDatabase(process.env.DATABASE_URL!);try{return NextResponse.json({items:(await pool.query('SELECT * FROM error_triggers ORDER BY name')).rows})}finally{await pool.end()}}
export async function POST(request:Request){const user=await requireRole('operator');const parsed=TriggerSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'invalid_body',issues:parsed.error.flatten()},{status:400});const b=parsed.data;const{pool}=createDatabase(process.env.DATABASE_URL!);try{const result=await pool.query(`INSERT INTO error_triggers(name,match_expr,severity,channels,throttle_seconds,active) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[b.name,b.matchExpr,b.severity,JSON.stringify(b.channels),b.throttleSeconds,b.active]);await pool.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'notification.trigger.create',$2,$3)`,[user.email,result.rows[0].id,result.rows[0]]);return NextResponse.json({item:result.rows[0]},{status:201})}finally{await pool.end()}}
export async function PATCH(request:Request){const user=await requireRole('operator');const parsed=TriggerSchema.required({id:true}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'invalid_body',issues:parsed.error.flatten()},{status:400});const b=parsed.data;const{pool}=createDatabase(process.env.DATABASE_URL!);try{const before=await pool.query('SELECT * FROM error_triggers WHERE id=$1',[b.id]);if(!before.rowCount)return NextResponse.json({error:'not_found'},{status:404});const result=await pool.query(`UPDATE error_triggers SET name=$2,match_expr=$3,severity=$4,channels=$5,throttle_seconds=$6,active=$7 WHERE id=$1 RETURNING *`,[b.id,b.name,b.matchExpr,b.severity,JSON.stringify(b.channels),b.throttleSeconds,b.active]);await pool.query(`INSERT INTO audit_log(actor_id,action,target,before,after) VALUES($1,'notification.trigger.update',$2,$3,$4)`,[user.email,b.id,before.rows[0],result.rows[0]]);return NextResponse.json({item:result.rows[0]})}finally{await pool.end()}}
export async function DELETE(request:Request){const user=await requireRole('admin');const id=z.string().uuid().safeParse(new URL(request.url).searchParams.get('id'));if(!id.success)return NextResponse.json({error:'invalid_id'},{status:400});const{pool}=createDatabase(process.env.DATABASE_URL!);try{const result=await pool.query('DELETE FROM error_triggers WHERE id=$1 RETURNING *',[id.data]);if(!result.rowCount)return NextResponse.json({error:'not_found'},{status:404});await pool.query(`INSERT INTO audit_log(actor_id,action,target,before) VALUES($1,'notification.trigger.delete',$2,$3)`,[user.email,id.data,result.rows[0]]);return NextResponse.json({ok:true})}finally{await pool.end()}}
