'use client'
import{FormEvent,useState}from'react'
import{appPath}from'@/lib/base-path'
const post=async(url:string,body:unknown)=>{const response=await fetch(appPath(url),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error??'Falha na operação');return value}
export function MultichannelActions({view}:{view:string}){const[message,setMessage]=useState('');const run=async(action:()=>Promise<unknown>)=>{setMessage('Enviando…');try{await action();setMessage('Operação concluída. Atualize a página para ver o resultado.')}catch(error){setMessage(error instanceof Error?error.message:'Erro inesperado')}}
if(view==='market-radar')return <Action title="Adicionar watch Reddit" message={message} onSubmit={(form)=>run(()=>post('/api/reddit/watches',{campaignId:text(form,'campaignId'),kind:text(form,'kind'),value:text(form,'value'),active:true}))}><Field name="campaignId" label="Campaign UUID"/><Select name="kind" options={['subreddit','search_query','user','keyword_across']}/><Field name="value" label="Subreddit, usuário ou consulta"/></Action>
if(view==='email-flows')return <Action title="Criar versão de fluxo" message={message} onSubmit={(form)=>run(()=>post('/api/email/flows',{campaignId:text(form,'campaignId'),name:text(form,'name'),description:text(form,'description'),active:false,entryCondition:{},steps:JSON.parse(text(form,'steps'))}))}><Field name="campaignId" label="Campaign UUID"/><Field name="name" label="Nome"/><Field name="description" label="Descrição"/><Field name="steps" label="Steps JSON" defaultValue='[{"id":"welcome","type":"send","message":{"from":"Rota <contato@example.com>","subject":"Bem-vindo","html":"<p>Olá</p>","plain":"Olá","kind":"transactional"}},{"id":"end","type":"end"}]'/></Action>
if(view==='conversations')return <Action title="Preparar mensagem WhatsApp" message={message} onSubmit={(form)=>run(()=>post('/api/whatsapp/messages',{conversationId:text(form,'conversationId'),kind:text(form,'kind'),text:text(form,'text')||undefined,templateRef:text(form,'templateRef')||undefined}))}><Field name="conversationId" label="Conversation UUID"/><Select name="kind" options={['text','template']}/><Field name="text" label="Texto dentro da janela de 24h"/><Field name="templateRef" label="Template aprovado (fora da janela)"/></Action>
if(view==='identities')return <Action title="Criar candidato de merge" message={message} onSubmit={(form)=>run(()=>post('/api/identities/candidates',{leadIdA:text(form,'leadIdA'),leadIdB:text(form,'leadIdB'),reason:text(form,'reason'),confidence:Number(text(form,'confidence')),verifiedEvidence:false}))}><Field name="leadIdA" label="Lead A UUID"/><Field name="leadIdB" label="Lead B UUID"/><Field name="reason" label="Evidência"/><Field name="confidence" label="Confiança 0–1" defaultValue="0.7"/></Action>
if(view==='contact-policies')return <Action title="Criar política" message={message} onSubmit={(form)=>run(()=>post('/api/contact-policies',{campaignId:text(form,'campaignId')||null,channel:text(form,'channel')||null,cadenceSeconds:Number(text(form,'cadenceSeconds')),enabled:true,rules:{}}))}><Field name="campaignId" label="Campaign UUID (vazio = global)"/><Select name="channel" options={['','instagram','threads','email','whatsapp']}/><Field name="cadenceSeconds" label="Cadência em segundos" defaultValue="86400"/></Action>;return null}
function Action({title,message,onSubmit,children}:{title:string;message:string;onSubmit:(form:FormData)=>void;children:React.ReactNode}){return <form className="multichannel-action" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();onSubmit(new FormData(event.currentTarget))}}><h2>{title}</h2><div className="multichannel-fields">{children}<button type="submit">Salvar</button></div>{message&&<p role="status">{message}</p>}</form>}
function Field({name,label,defaultValue}:{name:string;label:string;defaultValue?:string}){return <label>{label}<input name={name} defaultValue={defaultValue}/></label>};function Select({name,options}:{name:string;options:string[]}){return <label>{name}<select name={name}>{options.map(option=><option key={option} value={option}>{option||'global'}</option>)}</select></label>};const text=(form:FormData,name:string)=>String(form.get(name)??'').trim()
