import { createDatabase } from '@plataforma/db'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { getCampaignContext } from '@/lib/campaign-context'
import { requireRole } from '@/lib/permissions'
import { apiErrorResponse } from '@/lib/api-errors'

const CreateInput=z.object({title:z.string().min(3).max(160),description:z.string().min(3).max(3000),tenets:z.array(z.string().min(1)).default([]),forbiddenAngles:z.array(z.string().min(1)).default([]),toneGuidelines:z.string().max(2000).nullable().optional(),exampleHooks:z.array(z.string().min(1)).default([])})
const UpdateInput=CreateInput.partial().extend({id:z.string().uuid(),active:z.boolean().optional()})
const slugify=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)

export async function GET(){try{await requireRole('viewer');const{pool}=createDatabase(process.env.DATABASE_URL!);try{const{selected}=await getCampaignContext(pool);const items=(await pool.query(`SELECT thesis.*,count(item.id)::int content_count FROM theses thesis LEFT JOIN content_items item ON item.thesis_id=thesis.id WHERE ($1::uuid IS NULL OR thesis.campaign_id=$1) GROUP BY thesis.id ORDER BY thesis.active DESC,thesis.title`,[selected?.id??null])).rows;return NextResponse.json({data:items,meta:{requestId:crypto.randomUUID(),campaignId:selected?.id??null,generatedAt:new Date().toISOString(),sourceStatus:'ready'}})}finally{}}catch(error){return apiErrorResponse(error)}finally{}}
export async function POST(request:Request){const user=await requireRole('operator');const body=CreateInput.safeParse(await request.json().catch(()=>null));if(!body.success)return NextResponse.json({error:'invalid_request',issues:body.error.issues},{status:400});const{pool}=createDatabase(process.env.DATABASE_URL!);try{const{selected}=await getCampaignContext(pool);if(!selected)return NextResponse.json({error:'campaign_not_found'},{status:409});const item=(await pool.query(`INSERT INTO theses(campaign_id,slug,title,description,tenets,forbidden_angles,tone_guidelines,example_hooks) VALUES($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8::jsonb) RETURNING *`,[selected.id,slugify(body.data.title),body.data.title,body.data.description,JSON.stringify(body.data.tenets),JSON.stringify(body.data.forbiddenAngles),body.data.toneGuidelines??null,JSON.stringify(body.data.exampleHooks)])).rows[0];await pool.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'thesis.created',$2,$3)`,[user.email,item.id,item]);return NextResponse.json({item},{status:201})}catch(error){if(String(error).includes('more than seven'))return NextResponse.json({error:'active_thesis_limit'},{status:409});throw error}}
export async function PATCH(request:Request){try{const user=await requireRole('operator');const body=UpdateInput.safeParse(await request.json().catch(()=>null));if(!body.success)return NextResponse.json({error:'invalid_request',issues:body.error.issues},{status:400});const{pool}=createDatabase(process.env.DATABASE_URL!);const client=await pool.connect();try{await client.query('BEGIN');const before=(await client.query(`SELECT * FROM theses WHERE id=$1 FOR UPDATE`,[body.data.id])).rows[0];if(!before){await client.query('ROLLBACK');return NextResponse.json({error:'not_found'},{status:404})}const editorialChanged=['title','description','tenets','forbiddenAngles','toneGuidelines','exampleHooks'].some(key=>Object.prototype.hasOwnProperty.call(body.data,key));if(editorialChanged)await client.query(`INSERT INTO thesis_revisions(thesis_id,version,snapshot,changed_by) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT(thesis_id,version) DO NOTHING`,[before.id,before.version,JSON.stringify(before),user.email??null]);const item=(await client.query(`UPDATE theses SET title=COALESCE($2,title),description=COALESCE($3,description),tenets=COALESCE($4::jsonb,tenets),forbidden_angles=COALESCE($5::jsonb,forbidden_angles),tone_guidelines=COALESCE($6,tone_guidelines),example_hooks=COALESCE($7::jsonb,example_hooks),active=COALESCE($8,active),version=version+CASE WHEN $9 THEN 1 ELSE 0 END WHERE id=$1 RETURNING *`,[body.data.id,body.data.title??null,body.data.description??null,body.data.tenets?JSON.stringify(body.data.tenets):null,body.data.forbiddenAngles?JSON.stringify(body.data.forbiddenAngles):null,body.data.toneGuidelines??null,body.data.exampleHooks?JSON.stringify(body.data.exampleHooks):null,body.data.active??null,editorialChanged])).rows[0];await client.query(`INSERT INTO audit_log(actor_id,action,target,before,after) VALUES($1,'thesis.updated',$2,$3::jsonb,$4::jsonb)`,[user.email,item.id,JSON.stringify(before),JSON.stringify(item)]);await client.query('COMMIT');return NextResponse.json({item})}catch(error){await client.query('ROLLBACK').catch(()=>undefined);if(String(error).includes('more than seven'))return NextResponse.json({error:'active_thesis_limit'},{status:409});throw error}finally{client.release()}}catch(error){return apiErrorResponse(error)}finally{}}
