'use client'

import { DataTable, EmptyState, LiveBadge, PageHeader, PriorityChip } from '@plataforma/ui-bridge'
import { useState } from 'react'
interface Trigger{id:string;name:string;match_expr:string;severity:string;channels:string[];active:boolean;hit_count:number;last_hit_at:string|null}
interface Alert{id:string;kind:string;severity:'info'|'warn'|'error'|'critical';created_at:string;resolved_at:string|null;payload:Record<string,unknown>}
interface Delivery{id:string;channel:string;status:string;attempts:number;sent_at:string|null;last_error:string|null}
export function NotificationsClient({triggers,alerts,deliveries}:{triggers:Trigger[];alerts:Alert[];deliveries:Delivery[]}){const[tab,setTab]=useState('Triggers');const[testing,setTesting]=useState(false);const tabs=['Triggers','Canais','Incidentes','Entregas'];return <div className="page"><PageHeader title="Notificações & Erros" subtitle="Detecção, entrega e resposta operacional"/><nav className="tabs">{tabs.map((item)=><button key={item} aria-current={tab===item?'page':undefined} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  {tab==='Triggers'&&<section className="card"><h2>Triggers ({triggers.length})</h2>{triggers.map((item)=><article className="trigger-row" key={item.id}><div><strong>{item.name}</strong><code>{item.match_expr}</code></div><span>{item.severity}</span><span>{item.channels.join(', ')||'sem canal'}</span><label><input type="checkbox" checked={item.active} readOnly/> ativo</label></article>)}</section>}
  {tab==='Canais'&&<section className="card"><h2>Canais</h2><p><LiveBadge connected lastUpdate="agora"/> Webhook de notificações</p><button disabled={testing} onClick={async()=>{setTesting(true);await fetch('/prospector/api/admin/notifications/test',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});setTesting(false)}}>{testing?'Testando…':'Enviar teste manual'}</button></section>}
  {tab==='Incidentes'&&(alerts.length?<section className="incident-list">{alerts.map((item)=><article className="card" key={item.id}><header><PriorityChip priority={item.severity==='critical'?'P0':item.severity==='error'?'P1':'P2'}/><strong>{item.kind}</strong><time>{new Date(item.created_at).toLocaleString('pt-BR')}</time></header><pre className="json-preview">{JSON.stringify(item.payload,null,2)}</pre></article>)}</section>:<EmptyState message="Nenhum incidente registrado."/>)}
  {tab==='Entregas'&&<DataTable rows={deliveries} rowKey={(row)=>row.id} renderRow={(row)=><div className="delivery-row"><strong>{row.channel}</strong><span>{row.status}</span><span>{row.attempts} tentativas</span><time>{row.sent_at?new Date(row.sent_at).toLocaleString('pt-BR'):'—'}</time><span>{row.last_error??''}</span></div>}/>} </div>}
