import { createDatabase } from '@plataforma/db'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { getCampaignContext } from '@/lib/campaign-context'
import { requireRole } from '@/lib/permissions'

const Input=z.object({leadIds:z.array(z.string().uuid()).min(1).max(100),actionType:z.enum(['follow','like','reply'])})

export async function POST(request:Request){const user=await requireRole('operator');const parsed=Input.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'invalid_request'},{status:400});const{pool}=createDatabase(process.env.DATABASE_URL!);const client=await pool.connect();try{await client.query('BEGIN');const{selected}=await getCampaignContext(client);if(!selected){await client.query('ROLLBACK');return NextResponse.json({error:'campaign_not_found'},{status:409})}const account=(await client.query<{id:string}>(`SELECT id FROM accounts WHERE role='actor' ORDER BY (status='HEALTHY') DESC,username LIMIT 1`)).rows[0];if(!account){await client.query('ROLLBACK');return NextResponse.json({error:'actor_account_not_configured'},{status:409})}const leads=await client.query<{id:string;username_current:string;priority:'P0'|'P1'|'P2'|'P3'}>(`SELECT lead.id,lead.username_current,score.priority FROM leads lead JOIN lead_scores score ON score.lead_id=lead.id WHERE score.campaign_id=$1 AND lead.id=ANY($2::uuid[])`,[selected.id,parsed.data.leadIds]);let created=0;for(const lead of leads.rows){const result=await client.query(`INSERT INTO engagement_actions(account_id,lead_id,campaign_id,action_type,target_ref_type,target_ref_id,status,priority,reason_code,execution_mode,suggested_by) VALUES($1,$2,$3,$4,'profile',$5,'awaiting_approval',$6,'OPERATOR_BULK_PREPARE','api',$7) ON CONFLICT(account_id,lead_id,action_type,target_ref_id) DO NOTHING RETURNING id`,[account.id,lead.id,selected.id,parsed.data.actionType,lead.username_current,lead.priority,user.email]);if(result.rowCount){created++;await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'engagement.prepared',$2,$3::jsonb)`,[user.email,result.rows[0].id,JSON.stringify({leadId:lead.id,actionType:parsed.data.actionType,campaignId:selected.id})])}}await client.query('COMMIT');return NextResponse.json({created,requested:parsed.data.leadIds.length})}catch(error){await client.query('ROLLBACK');throw error}finally{client.release();await pool.end()}}
