export interface RedditThing { id: string; name: string; title?: string; selftext?: string; body?: string; author?: string; subreddit?: string; permalink?: string; score?: number; num_comments?: number; created_utc?: number }
export async function exchangeRedditRefreshToken(input: { clientId: string; clientSecret: string; refreshToken: string }) {
  const response = await fetch('https://www.reddit.com/api/v1/access_token', { method: 'POST', headers: { authorization: `Basic ${Buffer.from(`${input.clientId}:${input.clientSecret}`).toString('base64')}`, 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'refresh_token', refresh_token: input.refreshToken }) })
  if (!response.ok) throw new Error(`Reddit OAuth ${response.status}`)
  const body = await response.json() as { access_token?: string }
  if (!body.access_token) throw new Error('Reddit OAuth returned no access token')
  return body.access_token
}
export class RedditClient { private lastAt=0; constructor(private token:string,private userAgent:string,private baseUrl='https://oauth.reddit.com'){} private async get(path:string){const wait=Math.max(0,1000-(Date.now()-this.lastAt));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));this.lastAt=Date.now();const response=await fetch(`${this.baseUrl}${path}`,{headers:{authorization:`Bearer ${this.token}`,'user-agent':this.userAgent}});if(!response.ok)throw new Error(`Reddit API ${response.status}`);const data=await response.json() as {data?:{children?:Array<{data:RedditThing}>}};return data.data?.children?.map(item=>item.data)??[]} subreddit(name:string){return{new:()=>this.get(`/r/${encodeURIComponent(name)}/new.json`)}} search(query:string){return this.get(`/search.json?q=${encodeURIComponent(query)}&sort=new`)} user(name:string){return{comments:()=>this.get(`/user/${encodeURIComponent(name)}/comments.json`)}} comment(id:string){return{children:()=>this.get(`/comments/${encodeURIComponent(id)}.json`)}} }
