BEGIN;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE theses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid REFERENCES campaigns, slug text NOT NULL, title text NOT NULL, description text NOT NULL, tenets jsonb NOT NULL DEFAULT '[]', forbidden_angles jsonb DEFAULT '[]', tone_guidelines text, example_hooks jsonb DEFAULT '[]', centroid_embedding vector(384), version int NOT NULL DEFAULT 1, active boolean DEFAULT true, UNIQUE(campaign_id,slug,version));
CREATE TABLE content_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid REFERENCES campaigns, thesis_id uuid REFERENCES theses, audience_segment text, funnel_stage text CHECK(funnel_stage IN ('awareness','consideration','decision','retention')), objective text, angle text, hook text, arguments jsonb DEFAULT '[]', cta jsonb DEFAULT '{}', intelligence_sources jsonb DEFAULT '[]', brand_voice_version text NOT NULL, status text CHECK(status IN ('draft','approved','producing','published','archived','forked')) DEFAULT 'draft', created_by text, approved_by text, created_at timestamptz DEFAULT now(), approved_at timestamptz, frozen_at timestamptz, parent_id uuid REFERENCES content_items, UNIQUE(campaign_id,thesis_id,hook,funnel_stage));
CREATE TABLE content_item_theses (content_item_id uuid REFERENCES content_items ON DELETE CASCADE, thesis_id uuid REFERENCES theses, weight numeric NOT NULL DEFAULT 1.0 CHECK(weight > 0), PRIMARY KEY(content_item_id,thesis_id));
CREATE TABLE content_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), content_item_id uuid NOT NULL REFERENCES content_items ON DELETE CASCADE, channel text NOT NULL CHECK(channel IN ('instagram','threads','email','whatsapp_dm','whatsapp_group')), format text NOT NULL, payload jsonb NOT NULL, humanization_signature text, similarity_score numeric, generated_by text, status text CHECK(status IN ('draft','ready','approved','published','rejected','expired')) DEFAULT 'draft', approved_by text, published_at timestamptz, external_ref jsonb DEFAULT '{}', UNIQUE(content_item_id,channel,format));
CREATE TABLE content_publications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), variant_id uuid NOT NULL REFERENCES content_variants, channel text NOT NULL, external_id text, published_at timestamptz DEFAULT now(), metrics jsonb DEFAULT '{}');
CREATE TABLE reddit_watches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid REFERENCES campaigns, kind text CHECK(kind IN ('subreddit','search_query','user','keyword_across')), value text NOT NULL, active boolean DEFAULT true, min_interval_seconds int DEFAULT 900, max_interval_seconds int DEFAULT 21600, last_run_at timestamptz, next_run_at timestamptz, UNIQUE(kind,value));
CREATE TABLE reddit_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), watch_id uuid REFERENCES reddit_watches, external_kind text CHECK(external_kind IN ('post','comment')), external_id text NOT NULL, author_hash text, subreddit text, permalink text, text text, score int, num_comments int, posted_at timestamptz, collected_at timestamptz DEFAULT now(), embedding vector(384), UNIQUE(external_kind,external_id));
CREATE TABLE market_signals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid REFERENCES campaigns, kind text CHECK(kind IN ('pain_point','question','trend','comparison','commercial_intent','sentiment_shift')), label text NOT NULL, evidence_refs jsonb DEFAULT '[]', embedding vector(384), velocity_7d numeric, velocity_30d numeric, volume_current int, first_seen_at timestamptz DEFAULT now(), last_seen_at timestamptz DEFAULT now(), status text CHECK(status IN ('new','rising','stable','saturated','decaying')) DEFAULT 'new', linked_content_opportunity_id uuid REFERENCES content_opportunities);
CREATE TABLE email_subscribers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid REFERENCES leads, email citext NOT NULL UNIQUE, email_hash bytea NOT NULL, optin_source text NOT NULL, optin_evidence jsonb DEFAULT '{}', optin_at timestamptz DEFAULT now(), double_optin_at timestamptz, campaign_of_entry uuid REFERENCES campaigns, thesis_of_entry uuid REFERENCES theses, initial_topic text, unsubscribed_at timestamptz, unsubscribe_reason text, hard_bounced_at timestamptz);
CREATE TABLE email_flows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid REFERENCES campaigns, name text NOT NULL, description text, entry_condition jsonb NOT NULL DEFAULT '{}', steps jsonb NOT NULL DEFAULT '[]', active boolean DEFAULT false, version int NOT NULL DEFAULT 1, UNIQUE(campaign_id,name,version));
CREATE TABLE email_flow_state (subscriber_id uuid REFERENCES email_subscribers ON DELETE CASCADE, flow_id uuid REFERENCES email_flows ON DELETE CASCADE, current_step_id text, status text CHECK(status IN ('active','paused','completed','exited','suppressed')) DEFAULT 'active', entered_at timestamptz DEFAULT now(), next_evaluate_at timestamptz, PRIMARY KEY(subscriber_id,flow_id));
CREATE TABLE email_events (id bigserial PRIMARY KEY, subscriber_id uuid REFERENCES email_subscribers ON DELETE CASCADE, variant_id uuid REFERENCES content_variants, kind text CHECK(kind IN ('sent','delivered','opened','clicked','bounced','complained','replied','unsubscribed')), metadata jsonb DEFAULT '{}', at timestamptz DEFAULT now());
CREATE TABLE email_suppressions (email_hash bytea PRIMARY KEY, reason text CHECK(reason IN ('hard_bounce','complaint','unsubscribe','manual','list_purge')), suppressed_at timestamptz DEFAULT now(), notes text);
CREATE TABLE whatsapp_optins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid REFERENCES leads, phone_e164 text NOT NULL UNIQUE, phone_hash bytea NOT NULL, source text NOT NULL, evidence jsonb DEFAULT '{}', opted_in_at timestamptz DEFAULT now(), opted_out_at timestamptz, status text CHECK(status IN ('active','revoked','blocked')) DEFAULT 'active');
CREATE TABLE whatsapp_conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), optin_id uuid REFERENCES whatsapp_optins, lead_id uuid REFERENCES leads, wa_conversation_id text, stage text CHECK(stage IN ('opened','engaged','qualified','converted','cooled')) DEFAULT 'opened', last_inbound_at timestamptz, last_outbound_at timestamptz, session_window_expires_at timestamptz, requires_human_review boolean DEFAULT false);
CREATE TABLE whatsapp_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id uuid REFERENCES whatsapp_conversations, direction text CHECK(direction IN ('inbound','outbound')), kind text CHECK(kind IN ('text','template','image','audio','video','document','interactive')), template_ref text, text text, media_ref jsonb DEFAULT '{}', variant_id uuid REFERENCES content_variants, external_id text UNIQUE, status text CHECK(status IN ('queued','sent','delivered','read','failed')) DEFAULT 'queued', sent_at timestamptz, delivered_at timestamptz, read_at timestamptz);
CREATE TABLE whatsapp_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, category text, language text NOT NULL, body text NOT NULL, approval_status text NOT NULL CHECK(approval_status IN ('PENDING','APPROVED','REJECTED','PAUSED','DISABLED')), UNIQUE(name,language));
CREATE TABLE identities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id uuid REFERENCES leads, channel text NOT NULL CHECK(channel IN ('instagram','threads','email','whatsapp','reddit')), external_id text NOT NULL, external_handle text, verified boolean DEFAULT false, verified_via text CHECK(verified_via IN ('user_declared','oauth','otp','click_signed','import_confirmed')), verified_at timestamptz, evidence jsonb DEFAULT '{}', created_at timestamptz DEFAULT now(), UNIQUE(channel,external_id));
CREATE TABLE identity_candidates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), lead_id_a uuid REFERENCES leads, lead_id_b uuid REFERENCES leads, reason text, confidence numeric, evidence jsonb DEFAULT '{}', status text CHECK(status IN ('pending','approved','rejected','expired')) DEFAULT 'pending', decided_by text, decided_at timestamptz);
CREATE TABLE identity_merge_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), survivor_lead_id uuid REFERENCES leads, merged_lead_id uuid REFERENCES leads, snapshot jsonb NOT NULL, created_at timestamptz DEFAULT now(), expires_at timestamptz NOT NULL DEFAULT now() + interval '30 days', reverted_at timestamptz);
CREATE TABLE timeline_events (id bigserial PRIMARY KEY, lead_id uuid REFERENCES leads, channel text NOT NULL, event_type text NOT NULL, content_item_id uuid REFERENCES content_items, variant_id uuid REFERENCES content_variants, campaign_id uuid REFERENCES campaigns, external_ref jsonb DEFAULT '{}', metadata jsonb DEFAULT '{}', at timestamptz DEFAULT now(), source text CHECK(source IN ('api','scrape','webhook','manual','system')));
CREATE TABLE contact_policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id uuid REFERENCES campaigns, channel text, cadence_seconds int NOT NULL DEFAULT 86400, enabled boolean DEFAULT true, rules jsonb DEFAULT '{}');
ALTER TABLE lead_scores ADD COLUMN content_affinity jsonb DEFAULT '{}', ADD COLUMN email_engagement_score numeric DEFAULT 0, ADD COLUMN whatsapp_engagement_score numeric DEFAULT 0, ADD COLUMN freshness_score numeric DEFAULT 0;
ALTER TABLE nba_recommendations ADD COLUMN chosen_channel text;
ALTER TABLE accounts ADD COLUMN threads_user_id text, ADD COLUMN threads_rate_used_24h int DEFAULT 0, ADD COLUMN whatsapp_rate_used_1h int DEFAULT 0;
ALTER TABLE leads ADD COLUMN merged_into uuid REFERENCES leads;
CREATE INDEX content_items_campaign_status_idx ON content_items(campaign_id,status,funnel_stage); CREATE INDEX content_variants_item_channel_idx ON content_variants(content_item_id,channel); CREATE INDEX content_publications_variant_at_idx ON content_publications(variant_id,published_at DESC); CREATE INDEX timeline_events_lead_at_idx ON timeline_events(lead_id,at DESC); CREATE INDEX timeline_events_campaign_at_idx ON timeline_events(campaign_id,at DESC); CREATE INDEX reddit_evidence_subreddit_at_idx ON reddit_evidence(subreddit,posted_at DESC); CREATE INDEX market_signals_campaign_status_idx ON market_signals(campaign_id,status,velocity_7d DESC); CREATE INDEX email_subscribers_hash_idx ON email_subscribers(email_hash); CREATE INDEX email_events_subscriber_kind_at_idx ON email_events(subscriber_id,kind,at DESC); CREATE INDEX email_flow_state_active_idx ON email_flow_state(status,next_evaluate_at) WHERE status='active'; CREATE INDEX whatsapp_optins_hash_idx ON whatsapp_optins(phone_hash); CREATE INDEX whatsapp_conversations_lead_inbound_idx ON whatsapp_conversations(lead_id,last_inbound_at DESC); CREATE INDEX whatsapp_messages_conversation_sent_idx ON whatsapp_messages(conversation_id,sent_at DESC);

CREATE FUNCTION enforce_active_thesis_limit() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.active AND (TG_OP = 'INSERT' OR NOT OLD.active) AND (SELECT count(*) FROM theses WHERE campaign_id IS NOT DISTINCT FROM NEW.campaign_id AND active) >= 7 THEN RAISE EXCEPTION 'A campaign cannot have more than seven active theses'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER theses_active_limit BEFORE INSERT OR UPDATE OF active ON theses FOR EACH ROW EXECUTE FUNCTION enforce_active_thesis_limit();
CREATE FUNCTION enforce_content_item_frozen() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.frozen_at IS NOT NULL THEN RAISE EXCEPTION 'Published content items are immutable; create a fork'; END IF;
  IF NEW.frozen_at IS NOT NULL AND (to_jsonb(NEW) - 'frozen_at') IS DISTINCT FROM (to_jsonb(OLD) - 'frozen_at') THEN RAISE EXCEPTION 'Freezing a content item cannot change its content'; END IF;
  IF NEW.status = 'forked' AND NEW.parent_id IS NULL THEN RAISE EXCEPTION 'Forked content items require parent_id'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER content_items_frozen_guard BEFORE UPDATE ON content_items FOR EACH ROW EXECUTE FUNCTION enforce_content_item_frozen();
CREATE FUNCTION freeze_content_item_after_publication() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN UPDATE content_items SET frozen_at = COALESCE(frozen_at, NEW.published_at) WHERE id = (SELECT content_item_id FROM content_variants WHERE id = NEW.variant_id); RETURN NEW; END $$;
CREATE TRIGGER content_publications_freeze AFTER INSERT ON content_publications FOR EACH ROW EXECUTE FUNCTION freeze_content_item_after_publication();
CREATE FUNCTION enforce_whatsapp_window() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE expires_at timestamptz;
BEGIN
  IF NEW.direction = 'outbound' AND NEW.kind <> 'template' THEN SELECT session_window_expires_at INTO expires_at FROM whatsapp_conversations WHERE id = NEW.conversation_id; IF expires_at IS NULL OR expires_at <= now() THEN RAISE EXCEPTION 'WhatsApp free-form outbound requires an active 24h session window'; END IF; END IF;
  IF NEW.direction = 'outbound' AND NEW.kind = 'template' AND (NEW.template_ref IS NULL OR NOT EXISTS (SELECT 1 FROM whatsapp_templates WHERE name = NEW.template_ref AND approval_status = 'APPROVED')) THEN RAISE EXCEPTION 'WhatsApp outbound template must be Meta-approved'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER whatsapp_window_guard BEFORE INSERT OR UPDATE ON whatsapp_messages FOR EACH ROW EXECUTE FUNCTION enforce_whatsapp_window();
INSERT INTO identities(lead_id,channel,external_id,external_handle,verified) SELECT id,'instagram',username_current,username_current,false FROM leads WHERE username_current IS NOT NULL ON CONFLICT(channel,external_id) DO NOTHING;
COMMIT;
