BEGIN;
DROP FUNCTION IF EXISTS enforce_whatsapp_window();
DROP FUNCTION IF EXISTS freeze_content_item_after_publication();
DROP FUNCTION IF EXISTS enforce_content_item_frozen();
DROP FUNCTION IF EXISTS enforce_active_thesis_limit();
DROP TABLE IF EXISTS contact_policies;
DROP TABLE IF EXISTS timeline_events;
DROP TABLE IF EXISTS identity_candidates;
DROP TABLE IF EXISTS identity_merge_snapshots;
DROP TABLE IF EXISTS identities;
DROP TABLE IF EXISTS whatsapp_messages;
DROP TABLE IF EXISTS whatsapp_conversations;
DROP TABLE IF EXISTS whatsapp_optins;
DROP TABLE IF EXISTS whatsapp_templates;
DROP TABLE IF EXISTS email_suppressions;
DROP TABLE IF EXISTS email_events;
DROP TABLE IF EXISTS email_flow_state;
DROP TABLE IF EXISTS email_flows;
DROP TABLE IF EXISTS email_subscribers;
DROP TABLE IF EXISTS market_signals;
DROP TABLE IF EXISTS reddit_evidence;
DROP TABLE IF EXISTS reddit_watches;
DROP TABLE IF EXISTS content_publications;
DROP TABLE IF EXISTS content_variants;
DROP TABLE IF EXISTS content_item_theses;
DROP TABLE IF EXISTS content_items;
DROP TABLE IF EXISTS theses;
ALTER TABLE lead_scores DROP COLUMN IF EXISTS content_affinity, DROP COLUMN IF EXISTS email_engagement_score, DROP COLUMN IF EXISTS whatsapp_engagement_score, DROP COLUMN IF EXISTS freshness_score;
ALTER TABLE nba_recommendations DROP COLUMN IF EXISTS chosen_channel;
ALTER TABLE accounts DROP COLUMN IF EXISTS threads_user_id, DROP COLUMN IF EXISTS threads_rate_used_24h, DROP COLUMN IF EXISTS whatsapp_rate_used_1h;
ALTER TABLE leads DROP COLUMN IF EXISTS merged_into;
COMMIT;
