BEGIN;

REFRESH MATERIALIZED VIEW mv_content_performance WITH NO DATA;
REFRESH MATERIALIZED VIEW mv_conversation_funnel WITH NO DATA;
REFRESH MATERIALIZED VIEW mv_engagement_effectiveness WITH NO DATA;
REFRESH MATERIALIZED VIEW mv_campaign_performance WITH NO DATA;
REFRESH MATERIALIZED VIEW mv_daily_acquisition WITH NO DATA;
REFRESH MATERIALIZED VIEW mv_lead_rankings WITH NO DATA;
REFRESH MATERIALIZED VIEW mv_competitor_performance WITH NO DATA;

COMMIT;
