DROP TABLE IF EXISTS creative_bridge_deliveries;
DROP TABLE IF EXISTS organic_learning_recommendations;
DROP INDEX IF EXISTS content_publications_variant_window_unique;
DROP INDEX IF EXISTS content_publications_variant_channel_once;
ALTER TABLE content_publications DROP COLUMN IF EXISTS metric_window, DROP COLUMN IF EXISTS correlation_id;
ALTER TABLE content_variants DROP COLUMN IF EXISTS timezone, DROP COLUMN IF EXISTS scheduled_for;
DROP INDEX IF EXISTS scheduled_publications_channel_due_idx;
DROP INDEX IF EXISTS scheduled_publications_variant_channel_unique;
ALTER TABLE scheduled_publications DROP COLUMN IF EXISTS correlation_id, DROP COLUMN IF EXISTS channel;
ALTER TABLE content_items DROP COLUMN IF EXISTS content_version, DROP COLUMN IF EXISTS opportunity_id;
ALTER TABLE content_opportunities DROP COLUMN IF EXISTS source_references, DROP COLUMN IF EXISTS predicted_cost_usd, DROP COLUMN IF EXISTS confidence, DROP COLUMN IF EXISTS score_version, DROP COLUMN IF EXISTS score_components;
DROP TABLE IF EXISTS organic_intelligence_signals;
DROP TABLE IF EXISTS content_transcripts;
DROP TABLE IF EXISTS organic_comments;
DROP TABLE IF EXISTS content_metric_snapshots;
DROP TABLE IF EXISTS publication_metric_snapshots;
DROP TABLE IF EXISTS cross_platform_profiles;
DROP TABLE IF EXISTS cross_platform_entities;
DROP TABLE IF EXISTS organic_budget_reservations;
DROP TABLE IF EXISTS organic_budgets;
DROP TABLE IF EXISTS provider_usage;
DROP TABLE IF EXISTS provider_observations;
DROP TABLE IF EXISTS research_runs;
ALTER TABLE candidate_sources DROP CONSTRAINT IF EXISTS candidate_sources_discovered_via_check;
ALTER TABLE candidate_sources ADD CONSTRAINT candidate_sources_discovered_via_check CHECK(discovered_via IN ('collab','tag','mention','community_map','search','live'));
