'use client'

import { EmptyState, KpiCard, KpiRow, PageHeader, ThreePaneLayout } from '@plataforma/ui-bridge'
import { useCallback, useEffect, useState } from 'react'
import { appPath } from '@/lib/base-path'

interface ReviewItem { id:string;item_type:string;reason:string|null;suggested_action:Record<string,unknown>;context:Record<string,unknown>;created_at:string }
function label(value:string){return value.replace(/_/g,' ').replace(/^./,(character)=>character.toUpperCase())}
function ReadableRecord({value}:{value:Record<string,unknown>}){const entries=Object.entries(value);return entries.length?<dl className="record-list">{entries.map(([key,item])=><div key={key}><dt>{label(key)}</dt><dd>{item&&typeof item==='object'?Object.entries(item as Record<string,unknown>).map(([nested,nestedValue])=>`${label(nested)}: ${String(nestedValue)}`).join(' · '):String(item??'—')}</dd></div>)}</dl>:<p>Nenhuma informação adicional.</p>}

export function ReviewInboxClient({initialItems,decidedToday}:{initialItems:ReviewItem[];decidedToday:number}){
  const[items,setItems]=useState(initialItems),[index,setIndex]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[editing,setEditing]=useState(false),[editedText,setEditedText]=useState(''),[notes,setNotes]=useState('')
  const current=items[index]
  const decide=useCallback(async(action:'approve'|'edit'|'reject'|'block'|'snooze')=>{if(!current||busy)return;if(action==='edit'&&!editing){setEditedText(String(current.suggested_action.text??''));setEditing(true);return}setBusy(true);setMessage('');try{const payload:Record<string,unknown>={notes:notes||undefined};if(action==='snooze')payload.snoozeUntil=new Date(Date.now()+86_400_000).toISOString();if(action==='edit')payload.suggestedAction={...current.suggested_action,text:editedText};const response=await fetch(appPath(`/api/review-inbox/${current.id}/${action}`),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json() as {item?:ReviewItem;error?:string};if(!response.ok)throw new Error(body.error??'Não foi possível registrar a decisão');if(action==='edit'&&body.item){setItems((value)=>value.map((item)=>item.id===current.id?body.item!:item));setEditing(false);setMessage('Sugestão atualizada.')}else{setItems((value)=>value.filter((item)=>item.id!==current.id));setIndex(0);setMessage('Decisão registrada com auditoria.')}setNotes('')}catch(error){setMessage(error instanceof Error?error.message:'Erro inesperado')}finally{setBusy(false)}},[current,busy,editing,editedText,notes])
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.target as HTMLElement)?.matches('input,textarea'))return;const key=event.key.toLowerCase();if(key==='a')void decide('approve');else if(key==='e')void decide('edit');else if(key==='r')void decide('reject');else if(key==='b')void decide('block');else if(key==='.')void decide('snooze');else if(key==='j')setIndex((value)=>Math.min(items.length-1,value+1));else if(key==='k')setIndex((value)=>Math.max(0,value-1))};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[decide,items.length])
  return <div className="page"><PageHeader title="Review Inbox" subtitle="Triagem humana com contexto legível e trilha de auditoria"/><KpiRow><KpiCard label="Pendentes" value={items.length}/><KpiCard label="Decididos hoje" value={decidedToday}/></KpiRow><p className="keyboard-help">Atalhos: J/K navegar · A aprovar · E editar · R rejeitar · B bloquear · . adiar</p><p className="action-message" role="status">{message}</p>{!current?<EmptyState message={`Nada para revisar agora · ${decidedToday} decisões hoje`}/>:<ThreePaneLayout list={<><h2>Pendentes ({items.length})</h2>{items.map((item,itemIndex)=><button className="review-list-item" aria-current={itemIndex===index?'true':undefined} key={item.id} onClick={()=>{setIndex(itemIndex);setEditing(false);setNotes('')}}><strong>{label(item.item_type)}</strong><small>{item.reason}</small><time>{new Date(item.created_at).toLocaleString('pt-BR')}</time></button>)}</>} detail={<><p className="eyebrow">{label(current.item_type)}</p><h2>{current.reason??'Revisão necessária'}</h2>{editing?<label className="editor-field">Texto revisado<textarea value={editedText} onChange={(event)=>setEditedText(event.target.value)} rows={8}/></label>:<ReadableRecord value={current.suggested_action}/>}<label className="editor-field">Observação da decisão<textarea value={notes} onChange={(event)=>setNotes(event.target.value)} rows={3}/></label><div className="review-actions">{editing?<><button disabled={busy||!editedText.trim()} onClick={()=>void decide('edit')}>{busy?'Salvando…':'Salvar edição'}</button><button disabled={busy} onClick={()=>setEditing(false)}>Cancelar</button></>:<><button disabled={busy} onClick={()=>void decide('approve')}>A · Aprovar</button><button disabled={busy} onClick={()=>void decide('edit')}>E · Editar</button><button disabled={busy} onClick={()=>void decide('reject')}>R · Rejeitar</button><button disabled={busy} onClick={()=>void decide('block')}>B · Bloquear</button><button disabled={busy} onClick={()=>void decide('snooze')}>. · Adiar</button></>}</div></>} context={<><h2>Contexto</h2><ReadableRecord value={current.context}/><h3>Auditoria</h3><p>A decisão registra operador, estado anterior, estado final e horário no log imutável.</p></>}/>}</div>
}
