import { NextResponse } from 'next/server'
import { createDatabase, decryptToken, encryptToken } from '@plataforma/db'
import { requireRole } from '@/lib/permissions'
import { z } from 'zod'

const Provider=z.object({action:z.literal('save-provider'),id:z.string().uuid().optional(),name:z.string().trim().min(2).max(80),kind:z.enum(['openai-compatible','anthropic','local']),baseUrl:z.string().url(),apiKey:z.string().max(1000).optional(),enabled:z.boolean()})
const Model=z.object({action:z.literal('save-model'),id:z.string().uuid().optional(),providerId:z.string().uuid(),label:z.string().trim().min(2).max(120),modelId:z.string().trim().min(2).max(200),enabled:z.boolean(),isDefault:z.boolean(),supportsJson:z.boolean(),maxOutputTokens:z.number().int().min(64).max(32768),temperature:z.number().min(0).max(2)})
const SetDefault=z.object({action:z.literal('set-default'),modelId:z.string().uuid()})
const Test=z.object({action:z.literal('test'),providerId:z.string().uuid().optional(),modelId:z.string().uuid().optional()}).refine(value=>value.providerId||value.modelId,'Informe o provedor ou modelo')
const Input=z.discriminatedUnion('action',[Provider,Model,SetDefault,Test])

async function state(pool:ReturnType<typeof createDatabase>['pool']){const[providers,models]=await Promise.all([pool.query(`SELECT id,name,kind,base_url,enabled,api_key_encrypted IS NOT NULL has_api_key,updated_at FROM ai_providers ORDER BY name`),pool.query(`SELECT model.id,model.provider_id,provider.name provider_name,model.label,model.model_id,model.enabled,model.is_default,model.supports_json,model.max_output_tokens,model.temperature::float8 temperature,model.updated_at FROM ai_models model JOIN ai_providers provider ON provider.id=model.provider_id ORDER BY model.is_default DESC,provider.name,model.label`)]);return{providers:providers.rows,models:models.rows}}
function encryptionKey(){const value=process.env.TOKEN_ENCRYPTION_KEY;if(!value)throw new Error('TOKEN_ENCRYPTION_KEY não configurada');return Buffer.from(value,'base64')}

export async function GET(){await requireRole('viewer');const{pool}=createDatabase(process.env.DATABASE_URL!);try{return NextResponse.json(await state(pool))}finally{await pool.end()}}

export async function POST(request:Request){const user=await requireRole('admin');try{const body=Input.parse(await request.json()),{pool}=createDatabase(process.env.DATABASE_URL!);try{
 if(body.action==='save-provider'){const url=new URL(body.baseUrl);if(body.kind!=='local'&&url.protocol!=='https:')return NextResponse.json({error:'Provedores externos exigem HTTPS.'},{status:400});const existing=body.id?(await pool.query<{api_key_encrypted:string|null}>(`SELECT api_key_encrypted FROM ai_providers WHERE id=$1`,[body.id])).rows[0]:undefined;const encrypted=body.apiKey?.trim()?encryptToken(body.apiKey.trim(),encryptionKey()):existing?.api_key_encrypted??null;if(body.enabled&&body.kind!=='local'&&!encrypted)return NextResponse.json({error:'Informe uma chave antes de habilitar o provedor.'},{status:400});const row=body.id?(await pool.query(`UPDATE ai_providers SET name=$2,kind=$3,base_url=$4,api_key_encrypted=$5,enabled=$6,updated_at=now() WHERE id=$1 RETURNING id`,[body.id,body.name,body.kind,url.toString().replace(/\/$/,''),encrypted,body.enabled])).rows[0]:(await pool.query(`INSERT INTO ai_providers(name,kind,base_url,api_key_encrypted,enabled) VALUES($1,$2,$3,$4,$5) RETURNING id`,[body.name,body.kind,url.toString().replace(/\/$/,''),encrypted,body.enabled])).rows[0];await pool.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.provider.save',$2,$3::jsonb)`,[user.email??'unknown',String((row as{id:string}).id),JSON.stringify({name:body.name,kind:body.kind,baseUrl:url.toString(),enabled:body.enabled,hasApiKey:Boolean(encrypted)})]);return NextResponse.json({ok:true})}
 if(body.action==='save-model'){const client=await pool.connect();try{await client.query('BEGIN');if(body.isDefault)await client.query(`UPDATE ai_models SET is_default=false WHERE is_default`);const row=body.id?(await client.query(`UPDATE ai_models SET provider_id=$2,label=$3,model_id=$4,enabled=$5,is_default=$6,supports_json=$7,max_output_tokens=$8,temperature=$9,updated_at=now() WHERE id=$1 RETURNING id`,[body.id,body.providerId,body.label,body.modelId,body.enabled,body.isDefault,body.supportsJson,body.maxOutputTokens,body.temperature])).rows[0]:(await client.query(`INSERT INTO ai_models(provider_id,label,model_id,enabled,is_default,supports_json,max_output_tokens,temperature) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[body.providerId,body.label,body.modelId,body.enabled,body.isDefault,body.supportsJson,body.maxOutputTokens,body.temperature])).rows[0];await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.model.save',$2,$3::jsonb)`,[user.email??'unknown',String((row as{id:string}).id),JSON.stringify(body)]);await client.query('COMMIT');return NextResponse.json({ok:true})}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
 if(body.action==='set-default'){const client=await pool.connect();try{await client.query('BEGIN');await client.query(`UPDATE ai_models SET is_default=false WHERE is_default`);const result=await client.query(`UPDATE ai_models SET is_default=true,enabled=true,updated_at=now() WHERE id=$1 RETURNING model_id`,[body.modelId]);if(!result.rowCount)throw new Error('Modelo não encontrado');await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.model.default',$2,$3::jsonb)`,[user.email??'unknown',body.modelId,JSON.stringify({isDefault:true})]);await client.query('COMMIT');return NextResponse.json({ok:true})}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}
 const selected=(await pool.query<{kind:string;base_url:string;api_key_encrypted:string|null;model_id:string;max_output_tokens:number}>(`SELECT provider.kind,provider.base_url,provider.api_key_encrypted,model.model_id,model.max_output_tokens FROM ai_providers provider LEFT JOIN ai_models model ON model.provider_id=provider.id WHERE ${body.modelId?'model.id=$1':'provider.id=$1'} ORDER BY model.is_default DESC,model.enabled DESC LIMIT 1`,[body.modelId??body.providerId])).rows[0];if(!selected?.model_id)return NextResponse.json({error:'Cadastre um modelo para este provedor.'},{status:400});const key=selected.api_key_encrypted?decryptToken(selected.api_key_encrypted,encryptionKey()):'';if(selected.kind!=='local'&&!key)return NextResponse.json({error:'A chave do provedor não foi informada.'},{status:400});const started=Date.now(),anthropic=selected.kind==='anthropic',url=anthropic?`${selected.base_url.replace(/\/$/,'')}/v1/messages`:`${selected.base_url.replace(/\/$/,'')}/v1/chat/completions`,headers:Record<string,string>={'content-type':'application/json'};if(anthropic){headers['x-api-key']=key;headers['anthropic-version']='2023-06-01'}else if(key)headers.authorization=`Bearer ${key}`;const payload=anthropic?{model:selected.model_id,max_tokens:64,messages:[{role:'user',content:'Responda somente com OK.'}]}:{model:selected.model_id,max_tokens:64,messages:[{role:'user',content:'Responda somente com OK.'}]};const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload),signal:AbortSignal.timeout(20_000)});if(!response.ok)return NextResponse.json({error:`O provedor respondeu HTTP ${response.status}.`},{status:502});return NextResponse.json({ok:true,model:selected.model_id,latencyMs:Date.now()-started})
 }finally{await pool.end()}}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Falha inesperada'},{status:400})}}
