import { NextResponse } from 'next/server'
import { createDatabase } from '@plataforma/db'
import { apiErrorResponse, conflictResponse, invalidRequestResponse } from '@/lib/api-errors'
import { requireRole } from '@/lib/permissions'
import { z } from 'zod'

const catalog = {
  deepseek:{kind:'openai-compatible',baseUrl:'https://api.deepseek.com/v1',secret:'DEEPSEEK_API_KEY'},
  anthropic:{kind:'anthropic',baseUrl:'https://api.anthropic.com',secret:'ANTHROPIC_API_KEY'},
  openrouter:{kind:'openai-compatible',baseUrl:'https://openrouter.ai/api/v1',secret:'OPENROUTER_API_KEY'},
  zai:{kind:'openai-compatible',baseUrl:'https://api.z.ai/api/paas/v4',secret:'ZAI_API_KEY'},
  nvidia:{kind:'openai-compatible',baseUrl:'https://integrate.api.nvidia.com/v1',secret:'NVIDIA_API_KEY'},
  mistral:{kind:'openai-compatible',baseUrl:'https://api.mistral.ai/v1',secret:'MISTRAL_API_KEY'},
  opencode_go:{kind:'openai-compatible',baseUrl:'https://api.opencode.ai/v1',secret:'OPENCODE_GO_API_KEY'},
  wafer:{kind:'openai-compatible',baseUrl:'https://api.wafer.ai/v1',secret:'WAFER_API_KEY'},
  kimi:{kind:'openai-compatible',baseUrl:'https://api.moonshot.ai/v1',secret:'KIMI_API_KEY'},
  cerebras:{kind:'openai-compatible',baseUrl:'https://api.cerebras.ai/v1',secret:'CEREBRAS_API_KEY'},
  local:{kind:'local',baseUrl:'http://host.docker.internal:11434/v1',secret:null},
} as const
const Base=z.object({id:z.string().uuid().optional(),version:z.number().int().positive().optional()})
const Input=z.discriminatedUnion('action',[
  Base.extend({action:z.literal('save-provider'),catalogKey:z.enum(['deepseek','anthropic','openrouter','zai','nvidia','mistral','opencode_go','wafer','kimi','cerebras','local']),name:z.string().trim().min(2).max(80),enabled:z.boolean()}),
  Base.extend({action:z.literal('save-model'),providerId:z.string().uuid(),label:z.string().trim().min(2).max(120),modelId:z.string().trim().min(2).max(200),enabled:z.boolean(),isDefault:z.boolean(),supportsJson:z.boolean(),maxOutputTokens:z.number().int().min(64).max(32768),temperature:z.number().min(0).max(2)}),
  z.object({action:z.literal('set-default'),modelId:z.string().uuid(),version:z.number().int().positive()}), z.object({action:z.literal('reorder'),modelId:z.string().uuid(),direction:z.enum(['up','down']),version:z.number().int().positive()}), z.object({action:z.literal('remove-provider'),providerId:z.string().uuid(),version:z.number().int().positive(),reason:z.string().trim().min(3).max(500)}), z.object({action:z.literal('test'),modelId:z.string().uuid()})
])
const unavailable=(message:string,status=422)=>NextResponse.json({error:'invalid_state',message,traceId:crypto.randomUUID()},{status})
const isConfigured=(name:string|null)=>name===null||Boolean(process.env[name]?.trim())
async function state(pool:{query:Function}){const[providers,models,workers]=await Promise.all([
  pool.query(`SELECT id,name,kind,base_url,enabled,secret_env_name,secret_configured,sync_status,managed_origin,version,updated_at FROM ai_providers WHERE deleted_at IS NULL ORDER BY name`),
  pool.query(`SELECT model.id,model.provider_id,provider.name provider_name,model.label,model.model_id,model.enabled,model.is_default,model.priority,model.supports_json,model.max_output_tokens,model.temperature::float8 temperature,model.version,model.updated_at FROM ai_models model JOIN ai_providers provider ON provider.id=model.provider_id WHERE provider.deleted_at IS NULL ORDER BY model.is_default DESC,model.priority ASC,model.label`),
  pool.query(`SELECT worker,MAX(last_beat_at) last_beat_at,SUM(jobs_done_window)::int jobs_done_window,SUM(jobs_failed_window)::int jobs_failed_window FROM worker_heartbeats WHERE worker IN ('news-radar','content-opportunity','content-item-orchestrator') GROUP BY worker ORDER BY worker`)
]);return{providers:providers.rows,models:models.rows,workers:workers.rows,generatedAt:new Date().toISOString()}}
export async function GET(){try{await requireRole('viewer');const{pool}=createDatabase(process.env.DATABASE_URL!);try{return NextResponse.json(await state(pool))}finally{}}catch(error){return apiErrorResponse(error)}}
export async function POST(request:Request){let user:Awaited<ReturnType<typeof requireRole>>;try{user=await requireRole('admin')}catch(error){return apiErrorResponse(error)}const parsed=Input.safeParse(await request.json().catch(()=>null));if(!parsed.success)return invalidRequestResponse();const body=parsed.data,{pool}=createDatabase(process.env.DATABASE_URL!),client=await pool.connect();try{await client.query('BEGIN')
  if(body.action==='save-provider'){const item=catalog[body.catalogKey],configured=isConfigured(item.secret);if(body.enabled&&!configured){await client.query('ROLLBACK');return unavailable('A variável de ambiente do provedor ainda não está disponível no runtime.')}const result=body.id?await client.query(`UPDATE ai_providers SET name=$2,kind=$3,base_url=$4,secret_env_name=$5,secret_configured=$6,sync_status=$7,enabled=$8,managed_origin='manual',version=version+1,updated_at=now() WHERE id=$1 AND version=$9 AND deleted_at IS NULL RETURNING id`,[body.id,body.name,item.kind,item.baseUrl,item.secret,configured,configured?'synced':'missing_secret',body.enabled,body.version]):await client.query(`INSERT INTO ai_providers(name,kind,base_url,secret_env_name,secret_configured,sync_status,enabled,managed_origin) VALUES($1,$2,$3,$4,$5,$6,$7,'manual') RETURNING id`,[body.name,item.kind,item.baseUrl,item.secret,configured,configured?'synced':'missing_secret',body.enabled]);if(!result.rowCount){await client.query('ROLLBACK');return conflictResponse()}await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.provider.save',$2,$3::jsonb)`,[user.email??'unknown',result.rows[0].id,JSON.stringify({catalog:body.catalogKey,enabled:body.enabled,configured})])
  }else if(body.action==='save-model'){const provider=(await client.query<{enabled:boolean;secret_configured:boolean;kind:string}>(`SELECT enabled,secret_configured,kind FROM ai_providers WHERE id=$1 AND deleted_at IS NULL FOR UPDATE`,[body.providerId])).rows[0];if(!provider){await client.query('ROLLBACK');return unavailable('Provedor não encontrado.',404)}if(body.isDefault&&(!provider.enabled||(!provider.secret_configured&&provider.kind!=='local'))){await client.query('ROLLBACK');return unavailable('O provedor precisa estar ativo e configurado para ser padrão.')}if(body.isDefault)await client.query(`UPDATE ai_models SET is_default=false,version=version+1 WHERE is_default`);const priority=(await client.query<{priority:number}>(`SELECT COALESCE(MAX(priority),0)+10 priority FROM ai_models WHERE provider_id=$1`,[body.providerId])).rows[0]?.priority??10;const result=body.id?await client.query(`UPDATE ai_models SET provider_id=$2,label=$3,model_id=$4,enabled=$5,is_default=$6,supports_json=$7,max_output_tokens=$8,temperature=$9,version=version+1,updated_at=now() WHERE id=$1 AND version=$10 RETURNING id`,[body.id,body.providerId,body.label,body.modelId,body.enabled,body.isDefault,body.supportsJson,body.maxOutputTokens,body.temperature,body.version]):await client.query(`INSERT INTO ai_models(provider_id,label,model_id,enabled,is_default,priority,supports_json,max_output_tokens,temperature) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[body.providerId,body.label,body.modelId,body.enabled,body.isDefault,priority,body.supportsJson,body.maxOutputTokens,body.temperature]);if(!result.rowCount){await client.query('ROLLBACK');return conflictResponse()}await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.model.save',$2,$3::jsonb)`,[user.email??'unknown',result.rows[0].id,JSON.stringify({enabled:body.enabled,isDefault:body.isDefault})])
  }else if(body.action==='set-default'){const selected=(await client.query<{id:string}>(`SELECT model.id FROM ai_models model JOIN ai_providers provider ON provider.id=model.provider_id WHERE model.id=$1 AND model.version=$2 AND model.enabled AND provider.enabled AND provider.deleted_at IS NULL AND (provider.kind='local' OR provider.secret_configured) FOR UPDATE`,[body.modelId,body.version])).rows[0];if(!selected){await client.query('ROLLBACK');return unavailable('Modelo indisponível, desatualizado ou sem segredo configurado.')}await client.query(`UPDATE ai_models SET is_default=(id=$1),version=version+1,updated_at=now() WHERE is_default OR id=$1`,[selected.id]);await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.model.default',$2,'{"isDefault":true}')`,[user.email??'unknown',selected.id])
  }else if(body.action==='reorder'){const current=(await client.query<{id:string;priority:number}>(`SELECT id,priority FROM ai_models WHERE id=$1 AND version=$2 FOR UPDATE`,[body.modelId,body.version])).rows[0];if(!current){await client.query('ROLLBACK');return conflictResponse()}const adjacent=(await client.query<{id:string;priority:number}>(`SELECT id,priority FROM ai_models WHERE enabled AND id<>$1 ORDER BY priority ${body.direction==='up'?'DESC':'ASC'} LIMIT 1`,[current.id])).rows[0];if(adjacent)await client.query(`UPDATE ai_models SET priority=CASE WHEN id=$1 THEN $2 WHEN id=$3 THEN $4 END,version=version+1,updated_at=now() WHERE id IN ($1,$3)`,[current.id,adjacent.priority,adjacent.id,current.priority])
  }else if(body.action==='remove-provider'){const use=await client.query(`SELECT 1 FROM ai_models WHERE provider_id=$1 AND enabled LIMIT 1`,[body.providerId]);if(use.rowCount){await client.query('ROLLBACK');return unavailable('Desative os modelos do provedor antes de removê-lo.')}const result=await client.query(`UPDATE ai_providers SET enabled=false,deleted_at=now(),deleted_reason=$2,sync_status='tombstoned',version=version+1 WHERE id=$1 AND version=$3 AND deleted_at IS NULL RETURNING id`,[body.providerId,body.reason,body.version]);if(!result.rowCount){await client.query('ROLLBACK');return conflictResponse()}await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.provider.remove',$2,$3::jsonb)`,[user.email??'unknown',body.providerId,JSON.stringify({reason:body.reason})])
  }else{const selected=(await client.query<{provider_id:string;kind:string;base_url:string;secret_env_name:string|null;model_id:string}>(`SELECT provider.id provider_id,provider.kind,provider.base_url,provider.secret_env_name,model.model_id FROM ai_models model JOIN ai_providers provider ON provider.id=model.provider_id WHERE model.id=$1 AND model.enabled AND provider.enabled AND provider.deleted_at IS NULL`,[body.modelId])).rows[0];if(!selected){await client.query('ROLLBACK');return unavailable('Modelo não encontrado.',404)}const key=selected.secret_env_name?process.env[selected.secret_env_name]:undefined;if(selected.kind!=='local'&&!key){await client.query('ROLLBACK');return unavailable('O segredo do provedor não está disponível no runtime.')}const base=selected.base_url.replace(/\/$/,''),url=selected.kind==='anthropic'?`${base}/v1/messages`:`${base}${base.endsWith('/v1')?'':'/v1'}/chat/completions`,headers:Record<string,string>={'content-type':'application/json'};if(selected.kind==='anthropic'){headers['x-api-key']=key!;headers['anthropic-version']='2023-06-01'}else if(key)headers.authorization=`Bearer ${key}`;const started=Date.now(),response=await fetch(url,{method:'POST',headers,body:JSON.stringify(selected.kind==='anthropic'?{model:selected.model_id,max_tokens:16,messages:[{role:'user',content:'OK'}]}:{model:selected.model_id,max_tokens:16,messages:[{role:'user',content:'OK'}]}),signal:AbortSignal.timeout(20_000)}),latencyMs=Date.now()-started;if(!response.ok){await client.query(`INSERT INTO ai_provider_health(provider_id,model_id,status,latency_ms,error_code,tested_by) VALUES($1,$2,'degraded',$3,'provider_unavailable',$4)`,[selected.provider_id,body.modelId,latencyMs,user.email??null]);await client.query('COMMIT');return NextResponse.json({error:'provider_unavailable',traceId:crypto.randomUUID()},{status:502})}await client.query(`INSERT INTO ai_provider_health(provider_id,model_id,status,latency_ms,tested_by) VALUES($1,$2,'healthy',$3,$4)`,[selected.provider_id,body.modelId,latencyMs,user.email??null]);await client.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'ai.model.test',$2,$3::jsonb)`,[user.email??'unknown',body.modelId,JSON.stringify({latencyMs,result:'ok'})])}
  await client.query('COMMIT');return NextResponse.json({ok:true,state:await state(client)})
}catch(error){await client.query('ROLLBACK').catch(()=>undefined);return apiErrorResponse(error)}finally{client.release()}}
