export type DesignSystemPrimitive = 'button' | 'input' | 'badge' | 'card'
export const designSystemPackage = '@plataforma/design-system' as const
export * from './patterns'
export * from './tokens'
export * from './primitives'
export * from './fields'
export * from './dialogs'
export * from './feedback'
export * from './layout'
export * from './data'
export * from './help'
export * from './charts'
export * from './hooks'
