'use client'

import { useEffect, useRef, useState, type ReactNode } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'

export const PageHeader=({title,subtitle,actions}:{title:string;subtitle?:string;actions?:ReactNode})=><header className="page-header"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div>{actions}</div></header>
export const KpiCard=({label,value,delta}:{label:string;value:string|number;delta?:number})=><article className="card kpi"><span>{label}</span><strong>{value}</strong>{delta!==undefined&&<small aria-label={`Variação ${delta}%`}>{delta>=0?'↑':'↓'} {Math.abs(delta)}%</small>}</article>
export const KpiRow=({children}:{children:ReactNode})=><section className="kpi-row">{children}</section>
export const FilterBar=({filters,onClear}:{filters:string[];onClear?:()=>void})=><nav className="filter-bar" aria-label="Filtros">{filters.map((filter)=><button key={filter}>{filter}</button>)}{filters.length>0&&<button onClick={onClear}>Limpar filtros</button>}</nav>
export const SavedViewTabs=({views,active}:{views:string[];active:string})=><nav className="tabs">{views.map((view)=><button key={view} aria-current={view===active?'page':undefined}>{view}</button>)}<button>+ Nova view</button></nav>
export function DataTable<T>({rows,rowKey,renderRow}:{rows:T[];rowKey:(row:T)=>string;renderRow:(row:T)=>ReactNode}){const parent=useRef<HTMLDivElement>(null);const virtual=useVirtualizer({count:rows.length,getScrollElement:()=>parent.current,estimateSize:()=>44,overscan:8});return <div ref={parent} className="data-table" role="table"><div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map((item)=><div role="row" key={rowKey(rows[item.index]!)} style={{position:'absolute',transform:`translateY(${item.start}px)`,height:item.size,width:'100%'}}>{renderRow(rows[item.index]!)}</div>)}</div></div>}
export const RowActionsMenu=({children}:{children:ReactNode})=><details className="row-actions"><summary aria-label="Ações">⋯</summary>{children}</details>
export const RightDetailPane=({title,children,onClose}:{title:string;children:ReactNode;onClose?:()=>void})=><aside className="detail-pane"><header><h2>{title}</h2><button onClick={onClose} aria-label="Fechar">×</button></header>{children}</aside>
export const ThreePaneLayout=({list,detail,context}:{list:ReactNode;detail:ReactNode;context:ReactNode})=><div className="three-pane"><aside>{list}</aside><main>{detail}</main><aside>{context}</aside></div>
export const KanbanBoard=({columns}:{columns:Array<{title:string;items:ReactNode[]}>})=><div className="kanban">{columns.map((column)=><section key={column.title}><h2>{column.title}</h2>{column.items}</section>)}</div>
export const ScoreBadge=({score}:{score:number})=><span className={`score ${score>=80?'high':score>=50?'med':'low'}`}>{score>=80?'High':score>=50?'Med':'Low'} · {score}</span>
export const PriorityChip=({priority}:{priority:'P0'|'P1'|'P2'|'P3'})=><span className={`priority ${priority}`}>● {priority}</span>
export const ConfidencePill=({value}:{value:number})=><span className="confidence" aria-label={`Confiança ${value}%`}>◉ {value}%</span>
export const TimelineFeed=({events}:{events:Array<{id:string;kind:string;text:string;at:string;direction?:string;source?:string}>})=><ol className="timeline">{events.map((event)=><li key={event.id}><span>{event.direction==='inbound'?'←':event.direction==='outbound'?'→':'•'}</span><strong>{event.kind}</strong> {event.text}<small>{event.source} · {event.at}</small></li>)}</ol>
export const SuggestedActionCard=({title,rationale,confidence,onApprove}:{title:string;rationale:string;confidence:number;onApprove?:()=>void})=><article className="card suggestion"><h3>{title}</h3><ConfidencePill value={confidence}/><details><summary>Por quê?</summary>{rationale}</details><button onClick={onApprove}>Aprovar ação</button><button>Mandar para Review Inbox</button></article>
export const QuotaMeter=({used,limit}:{used:number;limit:number})=><div className="quota"><label>Usado {used}/{limit} · {Math.round(used/limit*100)}%</label><progress value={used} max={limit}/></div>
export const HealthDial=({value,state}:{value:number;state:string})=><div className="health" role="meter" aria-label={`Saúde: ${state}`} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><strong>{value}</strong><span>{state}</span></div>
export const EmptyState=({message,action}:{message:string;action?:ReactNode})=><section className="state empty"><span aria-hidden>◇</span><p>{message}</p>{action}</section>
export const ErrorState=({traceId,runbook,onRetry}:{traceId:string;runbook:string;onRetry?:()=>void})=><section className="state error"><strong>Não deu para carregar</strong><code>{traceId}</code><a href={runbook} target="_blank" rel="noreferrer">Runbook</a><button onClick={onRetry}>Tentar novamente</button></section>
export const LoadingSkeleton=({lines=3}:{lines?:number})=><div className="skeleton" aria-label="Carregando">{Array.from({length:lines},(_,index)=><span key={index}/>)}</div>
export function ConfirmDestructiveDialog({name,onConfirm}:{name?:string;onConfirm:()=>void}){const[ready,setReady]=useState(false);const[value,setValue]=useState('');useEffect(()=>{const timer=setTimeout(()=>setReady(true),3000);return()=>clearTimeout(timer)},[]);return <dialog open><h2>Confirmar ação destrutiva</h2><p>Esta ação pode afetar dados e não pode ser desfeita.</p>{name&&<input aria-label="Digite o nome para confirmar" value={value} onChange={(event)=>setValue(event.target.value)}/>}<button disabled={!ready||(name!==undefined&&value!==name)} onClick={onConfirm}>Confirmar</button></dialog>}
export const AsyncBanner=({kind='partial',children}:{kind?:string;children:ReactNode})=><div className={`banner ${kind}`} role="status">{children}</div>
export const LiveBadge=({connected,lastUpdate}:{connected:boolean;lastUpdate:string})=><span className={`live ${connected?'connected':'reconnecting'}`}><i/>{connected?'Ao vivo':'Reconectando…'} · {lastUpdate}</span>
export const RunbookLink=({href,name}:{href:string;name:string})=><a className="runbook" href={href} target="_blank" rel="noreferrer">▣ {name}</a>
export const RoleBadge=({role}:{role:'collector'|'actor'})=><span className={`role ${role}`}>{role==='collector'?'🕷 collector':'🎯 actor'}</span>
