'use client'

import { useEffect, useRef, useState, type ReactNode } from 'react'
import { useVirtualizer } from '@tanstack/react-virtual'
import Link from 'next/link'

export const FilterBar=({filters,onClear,onSelect}:{filters:string[];onClear?:()=>void;onSelect?:(filter:string)=>void})=><nav className="filter-bar" aria-label="Filtros ativos">{filters.map((filter)=>onSelect?<button type="button" key={filter} onClick={()=>onSelect(filter)}>{filter}</button>:<span className="filter-chip" key={filter}>{filter}</span>)}{filters.length>0&&onClear&&<button type="button" onClick={onClear}>Limpar filtros</button>}</nav>
import { motion } from 'framer-motion'
import { TabArrowButtons } from './TabNavigation'

export const SavedViewTabs=({views,active,onChange,onCreate}:{views:string[];active:string;onChange?:(view:string)=>void;onCreate?:()=>void})=>{const activeIndex=Math.max(0,views.indexOf(active));const previous=views[activeIndex-1];const next=views[activeIndex+1];return <div className="bridge-tab-navigation"><TabArrowButtons previous={previous&&onChange?{label:previous,onSelect:()=>onChange(previous)}:undefined} next={next&&onChange?{label:next,onSelect:()=>onChange(next)}:undefined}/><nav className="tabs" aria-label="Visualizações">{views.map((view)=><button type="button" key={view} aria-current={view===active?'page':undefined} onClick={onChange?()=>onChange(view):undefined} style={{ position: 'relative' }} disabled={!onChange}>{view}{view===active&&<motion.div layoutId="active-tab" style={{position:'absolute',bottom:0,left:0,right:0,height:2,backgroundColor:'var(--accent-primary)',borderRadius:1}}/>}</button>)}{onCreate&&<button type="button" onClick={onCreate}>+ Nova view</button>}</nav></div>}
export function DataTable<T>({rows,rowKey,renderRow,estimateSize=68,label='Dados'}:{rows:T[];rowKey:(row:T)=>string;renderRow:(row:T)=>ReactNode;estimateSize?:number;label?:string}){const parent=useRef<HTMLDivElement>(null);const virtual=useVirtualizer({count:rows.length,getScrollElement:()=>parent.current,estimateSize:()=>estimateSize,overscan:8,measureElement:(element)=>element.getBoundingClientRect().height});const height=Math.min(Math.max(rows.length*estimateSize,estimateSize),480);return <div ref={parent} className="data-table" role="table" aria-label={label} style={{height}}><div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map((item)=><div ref={virtual.measureElement} data-index={item.index} role="row" key={rowKey(rows[item.index]!)} style={{position:'absolute',transform:`translateY(${item.start}px)`,minHeight:item.size,width:'100%'}}>{renderRow(rows[item.index]!)}</div>)}</div></div>}
export const RowActionsMenu=({children}:{children:ReactNode})=><details className="row-actions"><summary aria-label="Ações">⋯</summary>{children}</details>
export const RightDetailPane=({title,children,onClose}:{title:string;children:ReactNode;onClose?:()=>void})=><aside className="detail-pane"><header><h2>{title}</h2><button onClick={onClose} aria-label="Fechar">×</button></header>{children}</aside>
export const KanbanBoard=({columns}:{columns:Array<{title:string;items:ReactNode[]}>})=><div className="kanban">{columns.map((column)=><section key={column.title}><h2>{column.title}</h2>{column.items}</section>)}</div>
export const PriorityChip=({priority}:{priority:'P0'|'P1'|'P2'|'P3'})=><span className={`priority ${priority}`}>● {priority}</span>
export const ConfidencePill=({value}:{value:number})=><span className="confidence" aria-label={`Confiança ${value}%`}>◉ {value}%</span>
export const TimelineFeed=({events}:{events:Array<{id:string;kind:string;text:string;at:string;direction?:string;source?:string}>})=><ol className="timeline">{events.map((event)=><li key={event.id}><span>{event.direction==='inbound'?'←':event.direction==='outbound'?'→':'•'}</span><strong>{event.kind}</strong> {event.text}<small>{event.source} · {event.at}</small></li>)}</ol>
export const SuggestedActionCard=({title,rationale,confidence,onApprove,onReview}:{title:ReactNode;rationale:string;confidence:number;onApprove?:()=>void;onReview?:()=>void})=><article className="card suggestion"><h3>{title}</h3><ConfidencePill value={confidence}/><details><summary>Por quê?</summary>{rationale}</details>{onApprove&&<button type="button" onClick={onApprove}>Aprovar ação</button>}{onReview&&<button type="button" onClick={onReview}>Mandar para Review Inbox</button>}</article>
export const QuotaMeter=({used,limit}:{used:number;limit:number})=><div className="quota"><label>{limit > 0 ? `Usado ${used}/${limit} · ${Math.round(used/limit*100)}%` : 'Limite não configurado'}</label>{limit > 0 ? <progress value={used} max={limit}/> : <span className="quota-unconfigured">Não medido</span>}</div>
export const HealthDial=({value,state}:{value:number;state:string})=><div className="health" role="meter" aria-label={`Saúde: ${state}`} aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}><strong>{value}</strong><span>{state}</span></div>
export const EmptyState=({message,action,title='Sem dados para exibir'}:{message:string;action?:ReactNode;title?:string})=><section className="state empty" role="status"><span className="state-mark" aria-hidden>◇</span><strong>{title}</strong><p>{message}</p>{action}</section>
export const ErrorState=({traceId,runbook,onRetry,message='A fonte não respondeu. Verifique o contexto e tente novamente.',impact='O restante da tela permanece disponível.'}:{traceId:string;runbook:string;onRetry?:()=>void;message?:string;impact?:string})=><section className="state error" role="alert"><strong>Não deu para carregar</strong><p>{message}</p><small>{impact}</small><code>traceId: {traceId}</code><Link href={runbook} target="_blank" rel="noreferrer">Abrir runbook</Link>{onRetry && <button type="button" onClick={onRetry}>Tentar novamente</button>}</section>
export function ConfirmDestructiveDialog({name,onConfirm}:{name?:string;onConfirm:()=>void|Promise<void>}){const[ready,setReady]=useState(false);const[value,setValue]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);useEffect(()=>{const timer=setTimeout(()=>setReady(true),3000);return()=>clearTimeout(timer)},[]);const confirm=async()=>{if(busy)return;setBusy(true);setError(null);try{await onConfirm()}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível concluir a ação.')}finally{setBusy(false)}};return <dialog open role="alertdialog" aria-busy={busy}><h2>Confirmar ação destrutiva</h2><p>Esta ação pode afetar dados e não pode ser desfeita.</p>{name&&<input aria-label="Digite o nome para confirmar" value={value} onChange={(event)=>setValue(event.target.value)} disabled={busy}/>} {error&&<p role="alert" style={{color:'var(--status-error)'}}>{error}</p>}<div className="action-row"><button type="button" disabled={!ready||busy||(name!==undefined&&value!==name)} onClick={() => void confirm()}>{busy?'Salvando…':'Confirmar'}</button></div></dialog>}
export const AsyncBanner=({kind='partial',children}:{kind?:string;children:ReactNode})=><div className={`banner ${kind}`} role="status">{children}</div>
import { Tooltip } from './feedback'

export const LiveBadge=({connected,lastUpdate,details}:{connected:boolean;lastUpdate:string;details?:string})=>{
  const badge = <span className={`live ${connected?'connected':'reconnecting'}`} style={{ cursor: 'help' }}><i/>{connected?'Ao vivo':'Reconectando…'} · {lastUpdate}</span>;
  return <Tooltip content={details || (connected ? 'Conexão em tempo real estabelecida com sucesso.' : 'Tentando reconectar ao servidor...')}>{badge}</Tooltip>;
}
export const RunbookLink=({href,name}:{href:string;name:string})=><Link className="runbook" href={href} target="_blank" rel="noreferrer">▣ {name}</Link>
export const RoleBadge=({role}:{role:'collector'|'actor'})=><span className={`role ${role}`}>{role==='collector'?'Coleta':'Ação'}</span>
export type MultichannelName = 'instagram'|'threads'|'email'|'whatsapp_dm'|'whatsapp_group'|'reddit'
export const ChannelBadge=({channel}:{channel:MultichannelName})=><span className={`channel-badge ${channel}`}>{channel.replace('_',' ')}</span>
export const ContentItemCard=({title,status,channels=[]}:{title:string;status:string;channels?:MultichannelName[]})=><article className="card content-item-card"><small>{status}</small><h3>{title}</h3><div>{channels.map((channel)=><ChannelBadge key={channel} channel={channel}/>)}</div></article>
export const VariantPreview=({channel,text,status='draft'}:{channel:MultichannelName;text:string;status?:string})=><article className="card variant-preview"><header><ChannelBadge channel={channel}/><small>{status}</small></header><p>{text}</p></article>
export const MarketSignalCard=({label,kind,velocity,evidenceCount,onOpen}:{label:string;kind:string;velocity:number;evidenceCount:number;onOpen?:()=>void})=><article className="card market-signal"><small>{kind}</small><h3>{label}</h3><p>Velocidade 7d: {velocity}</p>{onOpen?<button type="button" onClick={onOpen}>Ver {evidenceCount} evidências</button>:<span>{evidenceCount} evidências</span>}</article>
export const IdentityStrip=({identities}:{identities:Array<{channel:MultichannelName;handle:string;verified?:boolean}>})=><div className="identity-strip" aria-label="Identidades">{identities.map((identity)=><span key={`${identity.channel}:${identity.handle}`}><ChannelBadge channel={identity.channel}/>{identity.handle}{identity.verified?' ✓':''}</span>)}</div>
export const ChannelTimeline=({events}:{events:Array<{id:string;channel:MultichannelName;event:string;at:string}>})=><ol className="channel-timeline">{events.map((event)=><li key={event.id}><ChannelBadge channel={event.channel}/><strong>{event.event}</strong><time>{event.at}</time></li>)}</ol>
export const NbaWithChannel=({action,channel,rationale,confidence,onApprove,onReview}:{action:string;channel:MultichannelName;rationale:string;confidence:number;onApprove?:()=>void;onReview?:()=>void})=><SuggestedActionCard title={<><ChannelBadge channel={channel}/>{action}</>} rationale={rationale} confidence={confidence} onApprove={onApprove} onReview={onReview}/>
export const ContactPolicyIndicator=({allowed,reason}:{allowed:boolean;reason:string})=><span className={`policy-indicator ${allowed?'allowed':'blocked'}`} role="status">{allowed?'Contato permitido':'Contato bloqueado'} · {reason}</span>
export const OptinEvidenceCard=({source,at,status}:{source:string;at:string;status:string})=><article className="card optin-evidence"><h3>Opt-in {status}</h3><p>Origem: {source}</p><time>{at}</time></article>
export const FlowCanvas=({nodes=[]}:{nodes?:Array<{id:string;type:'Entry'|'Send'|'Wait'|'Branch'|'Exit';label:string}>})=><section className="flow-canvas" aria-label="Fluxo de e-mail">{nodes.length?nodes.map((node)=><article className="flow-node" draggable key={node.id}><small>{node.type}</small><strong>{node.label}</strong></article>):<EmptyState message="Nenhum nó no fluxo."/>}</section>
export const GroupPolicyForm=({available=false,onSave}:{available?:boolean;onSave?:(data:FormData)=>void})=><form className="group-policy-form" onSubmit={onSave?(event)=>{event.preventDefault();onSave(new FormData(event.currentTarget))}:(event)=>event.preventDefault()}><fieldset disabled={!available||!onSave}><legend>Política de grupos WhatsApp</legend><label>Frequência <input name="cadence" type="number" min="1" defaultValue={1}/></label><label><input name="salesCta" type="checkbox" defaultChecked={false}/> Permitir CTA de venda</label>{onSave&&<button>Salvar política</button>}</fieldset>{!available&&<AsyncBanner>WhatsApp Groups aguardando liberação da conta Meta.</AsyncBanner>}</form>

export const StatusBadge=({status}:{status:string})=><span className={`status-badge status-${status.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{status}</span>
export const IntegrationState=({name,status,detail,action}:{name:string;status:'ready'|'partial'|'not_configured'|'disabled'|'degraded'|'rate_limited'|'budget_blocked'|'error';detail:string;action?:ReactNode})=><article className={`card integration-state ${status}`}><div><strong>{name}</strong><StatusBadge status={status==='ready'?'Configurada':status==='partial'?'Parcial':status==='not_configured'?'Não configurada':status==='disabled'?'Desativada':status==='budget_blocked'?'Orçamento bloqueado':status==='rate_limited'?'Rate limited':status==='degraded'?'Degradada':'Erro'}/></div><p>{detail}</p>{action}</article>
