export const QUEUE_NAMES = [
  "discovery",
  "extraction",
  "meta-sync",
  "meta-webhook-consumer",
  "classification",
  "scoring",
  "enrichment",
  "engagement",
  "dm-copilot",
  "conversation-agent",
  "private-reply",
  "mention-monitor",
  "reciprocity-detector",
  "nba-engine",
  "competitive-intel",
  "content-opportunity",
  "community-map",
  "conversion-tracking",
  "data-quality",
  "alerts",
  "audience-overlap",
  "follower-mining",
  "search-mining",
  "collab-discovery",
  "live-monitor",
  "retention-tracker",
  "source-roi",
  "adaptive-crawler",
  "publisher",
  "content-item-orchestrator",
  "reddit-intelligence",
  "threads-adapter",
  "threads-publisher",
  "email-flow-engine",
  "email-events-consumer",
  "whatsapp-inbound",
  "whatsapp-outbound",
  "identity-resolver",
  "next-best-channel",
  "contact-policy-engine",
  "news-radar",
] as const;

export type QueueName = (typeof QUEUE_NAMES)[number];
