import { createDatabase } from '@plataforma/db'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireRole } from '@/lib/permissions'
const Step=z.object({id:z.string().min(1),type:z.enum(['send','wait_seconds','wait_until_event','branch_on','set_topic_affinity','exit_flow','end'])}).passthrough()
const Input=z.object({campaignId:z.string().uuid(),name:z.string().min(1).max(160),description:z.string().max(1000).optional(),entryCondition:z.record(z.string(),z.unknown()).default({}),steps:z.array(Step).min(1),active:z.boolean().default(false)})
export async function POST(request:Request){const user=await requireRole('admin'),input=Input.parse(await request.json()),{pool}=createDatabase(process.env.DATABASE_URL!);try{const row=(await pool.query<{id:string}>(`INSERT INTO email_flows(campaign_id,name,description,entry_condition,steps,active,version) SELECT $1,$2,$3,$4::jsonb,$5::jsonb,$6,COALESCE(max(version),0)+1 FROM email_flows WHERE campaign_id=$1 AND name=$2 RETURNING id`,[input.campaignId,input.name,input.description??null,JSON.stringify(input.entryCondition),JSON.stringify(input.steps),input.active])).rows[0]!;await pool.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'email_flow.create_version',$2,$3::jsonb)`,[user.email??'unknown',row.id,JSON.stringify(input)]);return NextResponse.json({ok:true,id:row.id},{status:201})}finally{await pool.end()}}
const Toggle=z.object({id:z.string().uuid(),active:z.boolean()})
export async function PATCH(request:Request){const user=await requireRole('admin'),input=Toggle.parse(await request.json()),{pool}=createDatabase(process.env.DATABASE_URL!);try{const row=(await pool.query(`UPDATE email_flows SET active=$2 WHERE id=$1 RETURNING *`,[input.id,input.active])).rows[0];if(!row)return NextResponse.json({error:'not_found'},{status:404});await pool.query(`INSERT INTO audit_log(actor_id,action,target,after) VALUES($1,'email_flow.toggle',$2,$3::jsonb)`,[user.email??'unknown',input.id,JSON.stringify({active:input.active})]);return NextResponse.json({item:row})}finally{await pool.end()}}
