import { createDatabase } from '@plataforma/db'
import { runWorker } from '@plataforma/queue/runtime'
import { createThreadsAdapter, spec, type ThreadsAdapterRepository } from './index.js'

const databaseUrl = process.env.DATABASE_URL
if (!databaseUrl) throw new Error('DATABASE_URL is required')
const { pool } = createDatabase(databaseUrl)
const repository: ThreadsAdapterRepository = { async get(id) { const result = await pool.query<{ id: string; campaign_id: string; angle: string; hook: string; arguments: unknown; brand_voice_version: string }>('SELECT id,campaign_id,angle,hook,arguments,brand_voice_version FROM content_items WHERE id=$1', [id]); const row = result.rows[0]; return row ? { id: row.id, campaignId: row.campaign_id, angle: row.angle, hook: row.hook, arguments: row.arguments, brandVoiceVersion: row.brand_voice_version } : null }, async recentTexts(campaignId) { return (await pool.query<{ text: string }>(`SELECT payload->>'text' text FROM content_variants variant JOIN content_items item ON item.id=variant.content_item_id WHERE item.campaign_id=$1 AND variant.channel='threads' AND item.created_at > now()-interval '30 days' LIMIT 50`, [campaignId])).rows.map((row) => row.text) }, async save(itemId, text) { return (await pool.query<{ id: string }>(`INSERT INTO content_variants(content_item_id,channel,format,payload,status,generated_by) VALUES($1,'threads','text',$2::jsonb,'ready','llm') ON CONFLICT(content_item_id,channel,format) DO UPDATE SET payload=EXCLUDED.payload,status='ready' RETURNING id`, [itemId, JSON.stringify({ text })])).rows[0]!.id }, async createReview(variantId, traceId) { await pool.query(`INSERT INTO review_inbox(item_type,item_ref_id,reason,suggested_action,context) VALUES('content_variant',$1,'Threads publication needs human approval',$2::jsonb,$3::jsonb)`, [variantId, JSON.stringify({ action: 'approve_threads_variant' }), JSON.stringify({ traceId })]) } }
const generate = async (prompt: string) => { const response = await fetch(process.env.LLM_ENDPOINT ?? '', { method: 'POST', headers: { 'content-type': 'application/json', ...(process.env.LLM_API_KEY ? { authorization: `Bearer ${process.env.LLM_API_KEY}` } : {}) }, body: JSON.stringify({ prompt, max_tokens: 180 }) }); if (!response.ok) throw new Error(`Threads generation failed: ${response.status}`); const body = await response.json() as { text?: string; choices?: Array<{ message?: { content?: string } }> }; return body.text ?? body.choices?.[0]?.message?.content ?? '' }
runWorker(spec.queue, createThreadsAdapter(repository, generate))
