export { TEyebrow } from './TEyebrow'
export { TFooter } from './TFooter'
export { TTitle } from './TTitle'
export { TBody } from './TBody'
export { TBox } from './TBox'
export { TTag } from './TTag'
export { TSlot } from './TSlot'
export { CanvasFrame } from './CanvasFrame'
