export type ApiAuthMode = 'public' | 'session'

export interface ApiRouteManifestEntry {
  path: string
  auth: ApiAuthMode
  methods: readonly ('GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE')[]
}

/** Generated from every route.ts under apps/web/src/app/api. Keep this list exhaustive. */
export const API_ROUTE_MANIFEST = [
  { path: '/api/admin/accounts/:id/policies', auth: 'session', methods: ['PATCH'] as const },
  { path: '/api/admin/ai', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/admin/automation-incidents/:id/acknowledge', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/automations', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/admin/automations/engines', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/admin/automations/engines/:key/run-now', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/automations/prerequisites', auth: 'session', methods: ['GET'] as const },
  { path: '/api/admin/competitor-insights/:id/action', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/competitors', auth: 'session', methods: ['GET', 'POST', 'PATCH'] as const },
  { path: '/api/admin/competitors/validate', auth: 'session', methods: ['GET'] as const },
  { path: '/api/admin/configs', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/content-suggestions/:id/action', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/notifications/count', auth: 'session', methods: ['GET'] as const },
  { path: '/api/admin/notifications/test', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/notifications/triggers', auth: 'session', methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] as const },
  { path: '/api/admin/organic-budgets', auth: 'session', methods: ['GET', 'PUT'] as const },
  { path: '/api/admin/organic-metrics', auth: 'session', methods: ['GET'] as const },
  { path: '/api/admin/publications', auth: 'session', methods: ['POST', 'PATCH'] as const },
  { path: '/api/admin/publishing/cancel', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/publishing/confirm-manual', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/publishing/kill-switch', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/admin/radar-findings/:id/action', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/research/run', auth: 'session', methods: ['POST'] as const },
  { path: '/api/admin/whatsapp-groups/availability', auth: 'session', methods: ['GET'] as const },
  { path: '/api/auth/:nextauth*', auth: 'public', methods: ['GET', 'POST'] as const },
  { path: '/api/auth/otp', auth: 'public', methods: ['POST'] as const },
  { path: '/api/contact-policies', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/contact-policies/evaluate', auth: 'session', methods: ['POST'] as const },
  { path: '/api/content-items', auth: 'session', methods: ['POST'] as const },
  { path: '/api/content-items/:id', auth: 'session', methods: ['PATCH', 'DELETE'] as const },
  { path: '/api/content-items/:id/approve', auth: 'session', methods: ['POST'] as const },
  { path: '/api/content-items/:id/fork', auth: 'session', methods: ['POST'] as const },
  { path: '/api/content-opportunities/:id', auth: 'session', methods: ['POST'] as const },
  { path: '/api/content-opportunities/:id/creative', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/content-variants/:id/schedule', auth: 'session', methods: ['POST'] as const },
  { path: '/api/content/funnel', auth: 'session', methods: ['GET'] as const },
  { path: '/api/context/campaign', auth: 'session', methods: ['POST'] as const },
  { path: '/api/creative-bridge', auth: 'session', methods: ['GET'] as const },
  { path: '/api/creative-bridge/:id', auth: 'session', methods: ['PATCH'] as const },
  { path: '/api/creative-bridge/:id/return', auth: 'session', methods: ['POST'] as const },
  { path: '/api/dashboard/:view', auth: 'session', methods: ['GET'] as const },
  { path: '/api/dashboard/today', auth: 'session', methods: ['GET'] as const },
  { path: '/api/email/confirm/:token', auth: 'public', methods: ['GET'] as const },
  { path: '/api/email/flows', auth: 'session', methods: ['POST', 'PATCH'] as const },
  { path: '/api/email/subscribe', auth: 'public', methods: ['POST'] as const },
  { path: '/api/email/webhook/:provider', auth: 'public', methods: ['POST'] as const },
  { path: '/api/engagement/actions', auth: 'session', methods: ['GET'] as const },
  { path: '/api/engagement/actions/:id', auth: 'session', methods: ['POST'] as const },
  { path: '/api/engagement/approve', auth: 'session', methods: ['POST'] as const },
  { path: '/api/health', auth: 'public', methods: ['GET'] as const },
  { path: '/api/health/live', auth: 'public', methods: ['GET'] as const },
  { path: '/api/health/operational', auth: 'public', methods: ['GET'] as const },
  { path: '/api/health/ready', auth: 'public', methods: ['GET'] as const },
  { path: '/api/identities/candidates', auth: 'session', methods: ['POST'] as const },
  { path: '/api/identities/candidates/:id/:action', auth: 'session', methods: ['POST'] as const },
  { path: '/api/identities/rollback/:id', auth: 'session', methods: ['POST'] as const },
  { path: '/api/integrations/capabilities', auth: 'session', methods: ['GET'] as const },
  { path: '/api/kill-switch', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/leads', auth: 'session', methods: ['GET'] as const },
  { path: '/api/leads/actions', auth: 'session', methods: ['POST'] as const },
  { path: '/api/market-watches', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/market-watches/canary', auth: 'session', methods: ['POST'] as const },
  { path: '/api/meta/oauth/callback', auth: 'public', methods: ['GET'] as const },
  { path: '/api/meta/oauth/start', auth: 'session', methods: ['GET'] as const },
  { path: '/api/meta/webhook', auth: 'public', methods: ['GET', 'POST'] as const },
  { path: '/api/metrics', auth: 'session', methods: ['GET'] as const },
  { path: '/api/reddit/watches', auth: 'session', methods: ['GET', 'POST'] as const },
  { path: '/api/review-inbox/:id/:action', auth: 'session', methods: ['POST'] as const },
  { path: '/api/theses', auth: 'session', methods: ['GET', 'POST', 'PATCH'] as const },
  { path: '/api/whatsapp/messages', auth: 'session', methods: ['POST'] as const },
  { path: '/api/whatsapp/optin', auth: 'public', methods: ['POST'] as const },
  { path: '/api/whatsapp/webhook', auth: 'public', methods: ['GET', 'POST'] as const },
] as const satisfies readonly ApiRouteManifestEntry[]
