import type { EmailMessage, EmailProvider } from '@plataforma/email-provider'
import { validateChannelText } from '@plataforma/humanizer'
import { createWorker, type WorkerJob, type WorkerResult, type WorkerSpec } from '@plataforma/shared/worker'
export const spec={queue:'email-flow-engine',requiresMetaToken:false} satisfies WorkerSpec
export type FlowStep={id:string;type:'send';message:Omit<EmailMessage,'to'>;variantId?:string;preheader?:string;next?:string}|{id:string;type:'wait_seconds';seconds:number;next?:string}|{id:string;type:'wait_until_event';event:string;next?:string}|{id:string;type:'branch_on';event:string;yes?:string;no?:string}|{id:string;type:'set_topic_affinity';topic:string;score:number;next?:string}|{id:string;type:'exit_flow'|'end'}
export interface FlowState{subscriberId:string;flowId:string;email:string;leadId?:string;currentStepId?:string;steps:FlowStep[];eventKinds:string[];suppressed:boolean;doubleOptin:boolean}
export interface FlowPayload{subscriberId?:string;flowId?:string;limit?:number}
export interface FlowRepository{due(payload:FlowPayload):Promise<FlowState[]>;sent(state:FlowState,step:Extract<FlowStep,{type:'send'}>,messageId:string):Promise<void>;advance(state:FlowState,next:string|undefined,at:Date|null,status?:'active'|'completed'|'exited'):Promise<void>;affinity(state:FlowState,topic:string,score:number):Promise<void>;review?(state:FlowState,step:Extract<FlowStep,{type:'send'}>,violations:string[]):Promise<void>}
const nextSequential=(state:FlowState,step:FlowStep)=>state.steps[state.steps.findIndex(item=>item.id===step.id)+1]?.id
export async function executeFlowStep(state:FlowState,repository:FlowRepository,provider:EmailProvider,now=new Date()){if(state.suppressed||!state.doubleOptin)throw Object.assign(new Error('Subscriber is not eligible'),{reasonCode:'PREFLIGHT_FAILED'});const step=state.steps.find(item=>item.id===(state.currentStepId??state.steps[0]?.id));if(!step){await repository.advance(state,undefined,null,'completed');return}const fallback=nextSequential(state,step);if(step.type==='send'){const validation=validateChannelText('email',step.message.plain,{subject:step.message.subject,preheader:step.preheader});if(!validation.ok){await repository.review?.(state,step,validation.violations);throw Object.assign(new Error('Email requires editorial review'),{reasonCode:'HUMANIZATION_REVIEW_REQUIRED',violations:validation.violations})}const delivery=await provider.send({...step.message,to:state.email});await repository.sent(state,step,delivery.messageId);await repository.advance(state,step.next??fallback,now)}else if(step.type==='wait_seconds')await repository.advance(state,step.next??fallback,new Date(now.getTime()+step.seconds*1000));else if(step.type==='wait_until_event'){if(state.eventKinds.includes(step.event))await repository.advance(state,step.next??fallback,now);else await repository.advance(state,step.id,new Date(now.getTime()+300000))}else if(step.type==='branch_on')await repository.advance(state,state.eventKinds.includes(step.event)?step.yes??fallback:step.no??fallback,now);else if(step.type==='set_topic_affinity'){await repository.affinity(state,step.topic,step.score);await repository.advance(state,step.next??fallback,now)}else await repository.advance(state,undefined,null,step.type==='exit_flow'?'exited':'completed')}
export function createEmailFlowProcessor(repository:FlowRepository,provider:EmailProvider){const gate=createWorker<FlowPayload>(spec);return async(job:WorkerJob<FlowPayload>):Promise<WorkerResult>=>{const base=await gate(job);const states=await repository.due(job.payload);for(const state of states)await executeFlowStep(state,repository,provider);return{...base,event:{kind:'email-flow.completed',payload:{evaluated:states.length}}}}}
